### ISSUE TITLE
你好，我发现如下文章有 bug:[第零章、核心框架汇总 > 一个方法团灭 nSum 问题]（https://labuladong.github.io/algo/1/15/）

### ISSUE THREAD

**Issue by eternal-heart** [labuladong/fucking-algorithm#1091]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[第零章、核心框架汇总 > 一个方法团灭 nSum 问题]（https://labuladong.github.io/algo/1/15/）

问题描述：
代码有问题，没有考虑相加后超过int类型的范围的情况。

**Comment by labuladong** [comment]
感谢反馈，最新版的文章已解决这个问题
