### ISSUE TITLE
bug 滑动窗口问题中，第三个例子最长无重复子串是不是有bug

### ISSUE THREAD

**Issue by mitliucak** [labuladong/fucking-algorithm#110]
[算法思维系列/滑动窗口技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3%E6%8A%80%E5%B7%A7.md)

问题描述：
这一讲中，第三个例子最长无重复子串，如果最长无重复子串解在起点（比如abcdc），答案是不是有问题。

某章图片链接失效/其中的 XXX 内容有误/等等。

**Comment by labuladong** [comment]
不是。
