### ISSUE TITLE
JetBrains 插件 bug 反馈

### ISSUE THREAD

**Issue by yanmin41295** [labuladong/fucking-algorithm#1103]
### Discussed in https://github.com/labuladong/fucking-algorithm/discussions/939

<div type='discussions-op-text'>

<sup>Originally posted by **labuladong** June  4, 2022</sup>
# 如果出现乱码

v1.4 及后续版本已修复这个问题，请更新最新版本插件。如果最新版本还出现乱码问题，参见 [这篇博客](https://blog.csdn.net/m0_38039437/article/details/104502838) 设置 IDE 的编码为 utf-8。

# 在你评论 Bug 之前，请先做以下几件事

1、进入插件市场，确保你安装插件是最新版本

2、看看下面有没有人和你遇到相同的问题

3、重启 IDE，或卸载重装插件，看看问题是否解决

# 若还是无法解决，按要求格式反馈 Bug

这不是bug!!!!,是改进建议
![image](https://user-images.githubusercontent.com/80966418/218305888-fc1442b5-f45f-4a8d-9e88-0a809288271d.png)

**Comment by Fenco-Han** [comment]
最新的UI启用之后，悬浮bar消失
![image](https://user-images.githubusercontent.com/52829373/220226876-4ea149c4-07bc-4a12-bdf5-0dcfd0acff97.png)
![image](https://user-images.githubusercontent.com/52829373/220227014-07675290-e723-401f-b375-b71d88ef40b4.png)

**Comment by labuladong** [comment]
目前还没完全适配新版 UI，一个替代方案是点击鼠标右键，也可以进行提交和测试

**Comment by bubble613** [comment]
为什么插件无法刷新问题数据

**Comment by RacerZ-fighting** [comment]
> 为什么插件无法刷新问题数据 ![image](https://user-images.githubusercontent.com/52210456/222941219-f3ef9c9c-6976-4b93-9c68-78f63f905f8b.png)

同问

**Comment by labuladong** [comment]
`[updateIfNecessary]` 这个是打印日志，没有问题的，下个版本 1.6.0 就不会显示了。另外，下个版本将提供多语言解法代码，敬请期待。

**Comment by labuladong** [comment]
PS：若有其他 bug，可以在 bug 反馈区 https://github.com/labuladong/fucking-algorithm/discussions/939 中讨论
