### ISSUE TITLE
[bug][{python}] {group-anagrams} 

### ISSUE THREAD

**Issue by TroyMai** [labuladong/fucking-algorithm#1119]
### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://leetcode.cn/problems/group-anagrams/

### 报错信息

```
解答失败:
	测试用例:["bdddddddddd","bbbbbbbbbbc"]
	测试结果:[["bbbbbbbbbbc","bdddddddddd"]]
	期望结果:[["bbbbbbbbbbc"],["bdddddddddd"]]
```

### 你是否愿意提交 PR 修复这个 bug？

- [X] 我愿意！

**Comment by labuladong** [comment]
Fixed by https://github.com/labuladong/fucking-algorithm/pull/1120
