### ISSUE TITLE
translate 技术/session和cookie.md

### ISSUE THREAD

**Issue by Funnyyanne** [labuladong/fucking-algorithm#119]
我已阅读过[翻译组工作流程](https://github.com/labuladong/fucking-algorithm/issues/9)，我已阅读过[翻译要求](https://github.com/labuladong/fucking-algorithm/blob/english/README.md)，我已查看 [已完成列表](https://github.com/labuladong/fucking-algorithm/pulls?q=is%3Apr+is%3Aclosed)，确保我要翻译的文章还没有被翻译。

我将开始翻译如下文章（点击可查看目标文章）：

[技术/session和cookie.md](https://github.com/labuladong/fucking-algorithm/blob/master/技术/session和cookie.md)

我对如何翻译此文章已经心中有数，我准备将它翻译成：**英文**

**预计 3 天内翻译完成**，我会尽可能快地完成翻译，主仓库会对第一个完成的 pull request 添加翻译者昵称/姓名及个人链接。

**Comment by ddgweb** [comment]
我提一句，session是以内存的形式存储，而不要简单以存储在服务器上来概括，以及为什么会占用服务器资源，就是当大量的用户占据session，就会占用内存，用session就要做好session池的管理方案。

**Comment by Funnyyanne** [comment]
> 我提一句，session是以内存的形式存储，而不要简单以存储在服务器上来概括，以及为什么会占用服务器资源，就是当大量的用户占据session，就会占用内存，用session就要做好session池的管理方案。
好的，我会加上的。

**Comment by Funnyyanne** [comment]
@ddgweb  好的，我会加上的。

> 我提一句，session是以内存的形式存储，而不要简单以存储在服务器上来概括，以及为什么会占用服务器资源，就是当大量的用户占据session，就会占用内存，用session就要做好session池的管理方案。

**Comment by Funnyyanne** [comment]
> @ddgweb 好的，我会加上的。
> 
> > 我提一句，session是以内存的形式存储，而不要简单以存储在服务器上来概括，以及为什么会占用服务器资源，就是当大量的用户占据session，就会占用内存，用session就要做好session池的管理方案。

@ddgweb  那段我会翻译成这个意思：session 是以内存的形式存储在服务器中，当大量的用户占据session，就会占用服务器资源，因此用session就要做好session池的管理方案。
