### ISSUE TITLE
translate 高频面试系列/k个一组反转链表.md

### ISSUE THREAD

**Issue by Justin-YGG** [labuladong/fucking-algorithm#13]
我将开始翻译如下文章（点击可查看目标文章）：

[动态规划系列/k个一组反转链表.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97/k%E4%B8%AA%E4%B8%80%E7%BB%84%E5%8F%8D%E8%BD%AC%E9%93%BE%E8%A1%A8.md)

我准备将它翻译成：**英文**

**预计 7 天内翻译完成**，若由于种种原因没有完成，如果你愿意，你可以接替我的工作翻译这篇文章。

**Comment by Iruze** [comment]
hi, your issue is duplicate with mine: https://github.com/labuladong/fucking-algorithm/issues/12
 and I am earlier occupy that one.
So can you choose another one, thank you!

**Comment by Justin-YGG** [comment]
done

**Comment by labuladong** [comment]
2020/3/1 update: 由于需要借助 Github Trending 推荐这波曝光，英文版需快速完成，所以更改之前的计划，任务不再具有抢占性，issue 中申明的时间不再有效，**主仓库会接受最先提交 pull request 的文章，认定提交者为翻译者，并且会在开头声明翻译者及其链接**。

请注意你的工作是否被其他人完成，详情见 [置顶 issue](https://github.com/labuladong/fucking-algorithm/issues/9)

**Comment by Justin-YGG** [comment]
ok 提前至今天完成
