### ISSUE TITLE
[bug][cpp] ti-huan-kong-ge-lcof

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#1358]
此 issue 的目的是修复 chatGPT 转译的多语言代码，更详细的背景信息和修复流程见：https://github.com/labuladong/fucking-algorithm/issues/1113

### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://leetcode.cn/problems/ti-huan-kong-ge-lcof/

### 报错信息

```
Line 521: Char 69: runtime error: applying non-zero offset 18446744073709551615 to null pointer (basic_string.h)
Line 521: Char 69: runtime error: applying non-zero offset 18446744073709551615 to null pointer (basic_string.h)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:531:69
```

### 你是否愿意提交 PR 修复这个 bug？

- [ ] 我愿意！

**Comment by huawuque404** [comment]
![image](https://user-images.githubusercontent.com/109327586/229704803-790dceb0-16b1-43c4-b977-2f28a55192cd.png)
这个代码在我这里没有问题
There is no problem with this code with me
