### ISSUE TITLE
[bug][javascript] vvXgSW

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#1360]
此 issue 的目的是修复 chatGPT 转译的多语言代码，更详细的背景信息和修复流程见：https://github.com/labuladong/fucking-algorithm/issues/1113

### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://leetcode.cn/problems/vvXgSW/

### 报错信息

```
Line 12: TypeError: pq.add is not a function
Line 12 in solution.js
            pq.add(head);
               ^
TypeError: pq.add is not a function
    Line 12: Char 16 in solution.js (mergeKLists)
    Line 36: Char 19 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 27: Char 26 in solution.js (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

### 你是否愿意提交 PR 修复这个 bug？

- [ ] 我愿意！

**Comment by onukwilip** [comment]
It says that `pq.add` is not a function, hence it's either `undefined`, `null` or another datatype. I suggest you do something like this to avoid the issue
```js
if (typeof pd?.add === "function") pd.add()
 ```

**Comment by Jayden12138** [comment]
> It says that `pq.add` is not a function, hence it's either `undefined`, `null` or another datatype. I suggest you do something like this to avoid the issue
> 
> ```js
> if (typeof pd?.add === "function") pd.add()
> ```

This is fine as far as error handling is concerned, but the main problem here is that the version of the third-party library introduced in leetcode is not always up-to-date, and he's in such an old version that he can't use these methods
[What are the environments for the programming languages?](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages)
Check out this link for details
