### ISSUE TITLE
[bug][cpp] zuo-xuan-zhuan-zi-fu-chuan-lcof

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#1369]
此 issue 的目的是修复 chatGPT 转译的多语言代码，更详细的背景信息和修复流程见：https://github.com/labuladong/fucking-algorithm/issues/1113

### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://leetcode.cn/problems/zuo-xuan-zhuan-zi-fu-chuan-lcof/

### 报错信息

```
Line 521: Char 69: runtime error: applying non-zero offset 18446744073709551615 to null pointer (basic_string.h)
Line 521: Char 69: runtime error: applying non-zero offset 18446744073709551615 to null pointer (basic_string.h)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:531:69
```

### 你是否愿意提交 PR 修复这个 bug？

- [ ] 我愿意！

**Comment by huawuque404** [comment]
![image](https://user-images.githubusercontent.com/109327586/229690433-155aadf6-7d16-4ca8-9bd9-55dd718ce9cb.png)
我这里运行没有问题唉
I have no problem here

**Comment by huawuque404** [comment]
![image](https://user-images.githubusercontent.com/109327586/229691372-c42a7a43-a6ff-4032-8f14-905563677817.png)
我这里没有问题唉
I have no problem here

**Comment by yjpi** [comment]
All language versions work fine
