### ISSUE TITLE
无法登陆，插件和clion全是目前的最新版。

### ISSUE THREAD

**Issue by qianyanglm** [labuladong/fucking-algorithm#1423]
账号密码登录不了win10系统。

**Comment by qianyanglm** [comment]
cookie可以登陆

**Comment by RickyLiu0w0** [comment]
> cookie可以登陆

请问cookie是复制`key`为`LEETCODE_SESSION`对应下的值吗？我用这个登陆返回：

> Users/username/.vscode/extensions/labuladong.leetcode-helper-1.4.4/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:549
>    return cb('invalid cookie?');
>                 ^
>
> TypeError: cb is not a function

**Comment by qianyanglm** [comment]
获取登陆的cookies

浏览器F12。console输入
javascript:document.cookie
或者看这个网址有说
https://blog.csdn.net/csdn_kou/article/details/124313332

Ricky Liu ***@***.***> 于2023年10月8日周日 09:32写道：
