### ISSUE TITLE
[bug][{c++}] {reverse-words-in-a-string/} 

### ISSUE THREAD

**Issue by GT-l** [labuladong/fucking-algorithm#1431]
### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://leetcode.cn/problems/reverse-words-in-a-string/

### 报错信息

解答错误
输入
s ="  hello world  "
输出
"world hello "

### 你是否愿意提交 PR 修复这个 bug？

- [X] 我愿意！

**Comment by GT-l** [comment]
class Solution {
public:
    string reverseWords(string s) {
        string res;
        // 清洗一下数据，去除多余的空格
        for (int i = 0; i < s.size(); i++) {
            char c = s[i];
            if (c != ' ') {
                // 单词中的字母/数字
                res += c;
            }
 
            else if (res.back() != ' ') {
                // 单词之间保留一个空格
                res += ' ';
            }
        }
        // 末尾如果有空格，清除之
        if (res.back() == ' ') {
            res.pop_back();
        }
 
        // 清洗之后的字符串
        char *chars = new char[res.size() + 1];
        strcpy(chars, res.c_str());
        int n = strlen(chars);
        // 进行单词的翻转，先整体翻转
        reverse(chars, 0, n - 1);
        // 再把每个单词翻转
        for (int i = 0; i < n; ) {
            for (int j = i; j < n; j++) {
                if (j + 1 == n || chars[j + 1] == ' ') {
                    // chars[i..j] 是一个单词，翻转之
                    reverse(chars, i, j);
                    // 把 i 置为下一个单词的首字母
                    i = j + 2;
                    break;
                }
            }
        }
        // 删除最后一个空格  
        if (chars[n - 1] == ' ') {  
            chars[n - 1] = '\0';  
            n--;  
        }  
        // 最后得到题目想要的结果
        return chars;
    }
 
    // 翻转 arr[i..j]
    void reverse(char* arr, int i, int j) {
        while (i < j) {
            char temp = arr[i];
            arr[i] = arr[j];
            arr[j] = temp;
            i++;
            j--;
        }
    }
};

**Comment by GT-l** [comment]
只需要在反转完之后判断最后一个是不是空格是的话去掉空格
// 删除最后一个空格  
        if (chars[n - 1] == ' ') {  
            chars[n - 1] = '\0';  
            n--;  
        }

**Comment by snowEyeOrz** [comment]
将清洗数据处理的
else if (res.back() != ' ')
改为else if(res!= "" && res.back()!=' ')
即可提交通过。
算法可视化的代码已经修正了
