### ISSUE TITLE
win 10 vsc 登录失败

### ISSUE THREAD

**Issue by RickyLiu0w0** [labuladong/fucking-algorithm#1476]
在`vsc`使用`labuladong`算法插件，使用**手机号+密码**的方式登录，发现无法登录，命令行输出：

> [ERROR] invalid password?

但我通过网页可以保证我输入的密码无误

请问如何查看日志判断插件是否正确读取了我输入的账号和密码？

**Comment by Frozen-hc** [comment]
我也遇到了同样的问题，国内版无法登录

**Comment by zyqhnu** [comment]
[ERROR] session expired, please login again [code=-1]

**Comment by zyqhnu** [comment]
> 

Failed to sign in. Please open the output channel for details
