### ISSUE TITLE
用密码或cookie登录失败，output panel有报错

### ISSUE THREAD

**Issue by xflcx1991** [labuladong/fucking-algorithm#1479]
vscode 1.81.1，插件版本 1.4.2，系统：Ubuntu 18.04
nvm安装的node，版本：v16.19.1
无论是选择密码还是cookie登录，都提示同样的`return cb()`报错

 
[ERROR] You are not login yet?
(node:8868) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8887) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:8897) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
cookie: /home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:549
    return cb('invalid cookie?');
           ^

TypeError: cb is not a function
    at parseCookie (/home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:549:12)
    at Plugin.plugin.cookieLogin (/home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:572:22)
    at /home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/vsc-leetcode-cli/lib/commands/user.js:119:12
    at /home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/prompt/lib/prompt.js:336:32
    at /home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/prompt/lib/prompt.js:333:9)
    at /home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/prompt/lib/prompt.js:342:32
    at /home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/home/qcraft/.vscode/extensions/labuladong.leetcode-helper-1.4.2/node_modules/read/lib/read.js:111:5)
    at Interface.emit (node:events:513:28)

**Comment by Adeshen** [comment]
我也同样遇到了这个问题

**Comment by peertechz** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
lindadev77, @ikuju, @johnqxu, @80000v, @rebill, @kamechen, @FireTercel, @SinNiSoipor, @ASH-L-CN, @helen-frank, @wuwulailai, @Thunderlbc, @marguin, @Redbaron0601, @ZinniaSun2000, @shaojava, @603232357, @TOMchengxianguan, @heiheiwanne, @fengjw1

**Comment by PCB-CPU** [comment]
同样遇到该问题
