### ISSUE TITLE
translate 动态规划系列/动态规划之KMP字符匹配算法.md

### ISSUE THREAD

**Issue by FengYuQ** [labuladong/fucking-algorithm#15]
我将开始翻译如下文章（点击可查看目标文章）：

[动态规划系列/动态规划之KMP字符匹配算法.md](https://github.com/labuladong/fucking-algorithm/blob/master/动态规划系列/动态规划之KMP字符匹配算法.md)

我准备将它翻译成：**英文**

**预计30 天内翻译完成**，若由于种种原因没有完成，如果你愿意，你可以接替我的工作翻译这篇文章。

**Comment by labuladong** [comment]
占有时间过长，一篇文章几千字，平均一篇文章不得超过十天，我将 label 设为了 `invalid`，请重新评估时间，然后再将 label 设置为 `translate`。
