### ISSUE TITLE
[bug][C++] 146 LRU缓存

### ISSUE THREAD

**Issue by ClarkArden** [labuladong/fucking-algorithm#1511]
### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://labuladong.github.io/algo/di-yi-zhan-da78c/shou-ba-sh-daeca/suan-fa-ji-8674e/

### 报错信息

146 题   LRU 缓存   C++ 版本的解法错误，  因为C++ 中的 unordered_map是无序的导致错误

### 你是否愿意提交 PR 修复这个 bug？

- [ ] 我愿意！

**Comment by krushnarout** [comment]
I can work on this issue.
