### ISSUE TITLE
bug 已知链表中含有环，返回这个环的起始位置

### ISSUE THREAD

**Issue by linuxholic** [labuladong/fucking-algorithm#152]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/双指针技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%8F%8C%E6%8C%87%E9%92%88%E6%8A%80%E5%B7%A7.md)

问题描述：

其中关于 k 的表述，k 应该是 环长度 的整数倍，而不一定刚好是环的长度

**Comment by GYee** [comment]
> 你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：
> 
> [算法思维系列/双指针技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%8F%8C%E6%8C%87%E9%92%88%E6%8A%80%E5%B7%A7.md)
> 
> 问题描述：
> 
> 其中关于 k 的表述，k 应该是 环长度 的整数倍，而不一定刚好是环的长度

对头，k应该是环长度的整数倍。刚想提issue纠正就看到你的，支持一下

**Comment by yzydhf** [comment]
> 收到，我将查看相关文章并修改

问题还没有改呀

**Comment by yzydhf** [comment]
https://github.com/labuladong/fucking-algorithm/issues/152#issue-575502235
你好  关于这个问题  好像还没有改正呀

**Comment by GreenGums** [comment]
这里我依旧认为 K应该就恰好是环的长度，而不是你们说的整数倍。
假设环长为N，慢指针前进N步时，快指针前进了2N。因为快指针比慢指针多走了一个环的长度。所以，快慢指针会相遇

**Comment by GreenGums** [comment]
之所以认为第一次相遇是整数倍而不是刚好一倍主要是考虑到快指针跳过慢指针的情况：
    上一步快指针在慢指针后面，下一步快指针就在慢指针前面了，没有相遇。
    然而这种情况仅仅存在于慢指针一次走的步数大于1的情况。
    对应我上面说的，就是环的长度为5，慢指针一次走一步，这样我上面说的环长为N，然而慢指针不可能走N，因为慢指针一次两步

**Comment by labuladong** [comment]
@GreenGums 是整数倍，你设想一下，比如说，环的长度只有 3，到环起点之前的链表长度有 100，那么快指针肯定是先到环里绕圈圈了，等慢指针过来之后，肯定是不只是一个环的长度。

**Comment by GreenGums** [comment]
> @GreenGums 是整数倍，你设想一下，比如说，环的长度只有 3，到环起点之前的链表长度有 100，那么快指针肯定是先到环里绕圈圈了，等慢指针过来之后，肯定是不只是一个环的长度。

确实是我想错了，感谢解答。
