### ISSUE TITLE
关闭下载PDF就说清楚

### ISSUE THREAD

**Issue by mkx000** [labuladong/fucking-algorithm#1533]
作者吃相真难看，已经不给下载PDF了，直接在READEME上说出来多好。先诱导我关注微信公众号，最后饶了一大圈到百度网盘下载个PDF文件说关闭下载，无语。。。。。

**Comment by cultivater** [comment]
+1 纯粹浪费人时间，恶心

**Comment by labuladong** [comment]
对不起，没注意到你们的评论，很抱歉没能帮助到你们
