### ISSUE TITLE
获取题目列表错误

### ISSUE THREAD

**Issue by nowscott** [labuladong/fucking-algorithm#1545]
获取题目列表错误，昨天开始一直获取错误，今天重新登陆还是遇到这个问题

**Comment by Nwavguy** [comment]
我的也坏了

**Comment by alexya** [comment]
嗯，好像leetcode原始的插件也坏了...... 
https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/928
https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/927
不知道咋弄 :cry:

**Comment by labuladong** [comment]
v1.5.3 已修复这个问题，预计十分钟后完成发布。
