### ISSUE TITLE
[bug][java] 310. Minimum Height Trees

### ISSUE THREAD

**Issue by zichengl** [labuladong/fucking-algorithm#1566]
### 请在提交 bug 之前先搜索

- [X] 我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。

### 出错的题目链接

https://leetcode.com/problems/minimum-height-trees/description/

### 报错信息

1. 编译报错 For Loop 之后缺少 leaves = newLeaves 这一行
2. For Loop 需要使用 Boxed Type 不能使用 Primitive Type, 不然Array List 在Remove的时候会当成Index 来操作
3. 缺少 N = 0 的检查

### 你是否愿意提交 PR 修复这个 bug？

- [X] 我愿意！

**Comment by PushpitSB** [comment]
can you show your code
