### ISSUE TITLE
translate 算法思维系列/前缀和技巧.md + 算法思维系列/滑动窗口技巧.md + 算法思维系列/信封嵌套问题.md

### ISSUE THREAD

**Issue by Iruze** [labuladong/fucking-algorithm#16]
我将开始翻译如下文章（点击可查看目标文章）：

[算法思维系列/前缀和技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%89%8D%E7%BC%80%E5%92%8C%E6%8A%80%E5%B7%A7.md) + [算法思维系列/滑动窗口技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3%E6%8A%80%E5%B7%A7.md)  + [算法思维系列/信封嵌套问题.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E4%BF%A1%E5%B0%81%E5%B5%8C%E5%A5%97%E9%97%AE%E9%A2%98.md)

我准备将它翻译成：**英文**

**预计 14 天内翻译完成**，若由于种种原因没有完成，如果你愿意，你可以接替我的工作翻译这篇文章。

**Comment by labuladong** [comment]
2020/3/1 update: 由于需要借助 Github Trending 推荐这波曝光，英文版需快速完成，所以更改之前的计划，任务不再具有抢占性，issue 中申明的时间不再有效，**主仓库会接受最先提交 pull request 的文章，认定提交者为翻译者，并且会在开头声明翻译者及其链接**。

请注意你的工作是否被其他人完成，详情见 [置顶 issue](https://github.com/labuladong/fucking-algorithm/issues/9)

**Comment by youyun** [comment]
Hey, I've submitted PR for your first article, Prefix Sum.
Issue: https://github.com/labuladong/fucking-algorithm/issues/137
PR: https://github.com/labuladong/fucking-algorithm/pull/138
