### ISSUE TITLE
网站展示问题

### ISSUE THREAD

**Issue by SuperZ3** [labuladong/fucking-algorithm#1608]
网站展示异常，太小了，手机模式是正常的
<img width="2044" alt="截屏2024-07-29 09 46 18" src="https://github.com/user-attachments/assets/37cf12e8-463c-49c1-bf01-a710976ed745">

**Comment by labuladong** [comment]
这有点夸张。。。是不是你的显示器太宽了？

**Comment by SuperZ3** [comment]
> 这有点夸张。。。是不是你的显示器太宽了？
不好意思，我的问题，我把这个关了吧
