### ISSUE TITLE
提交代码报错

### ISSUE THREAD

**Issue by wttgt** [labuladong/fucking-algorithm#1613]
![2W@VV4QJ(D5N29QF`)$ORJF](https://github.com/user-attachments/assets/190f1f88-977f-47d8-92fe-79d214f8f1b1)
为什么会这样报错呀？

**Comment by labuladong** [comment]
你的用法不对。不是自己运行代码，而是点击 submit/test 按钮提交代码

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c80fbbd3-3693-4e8d-9661-83ef65e3a1d4">

**Comment by wttgt** [comment]
谢谢，了解了
