### ISSUE TITLE
labuladong.online 打不开了 

### ISSUE THREAD

**Issue by oliverwreath** [labuladong/fucking-algorithm#1614]
**Version:**
What's the extension version are you using?

**Describe the bug**
本来上上周好端端开着的链接，大概上周再开就host unknown了。
URL: https://labuladong.online/algo/frequency-interview/trapping-rain-water/

**Platform**
Windows PC?
![image](https://github.com/user-attachments/assets/199232bb-d6dd-4b33-b41b-3219b98dc3de)
What kind of web browser? (chrome/edge/...)
![image](https://github.com/user-attachments/assets/47f74f7d-56c1-4104-8e79-90c5e1031a60)

**Comment by labuladong** [comment]
你是什么中国大陆的网络，还是海外网络？是否有挂代理？

这种情况一般是本地网络的问题，可是更换网络试下？
