### ISSUE TITLE
清空历史记录以后无法正常查看“思路”

### ISSUE THREAD

**Issue by Joan-gao** [labuladong/fucking-algorithm#1615]
如题。之前都正常显示，清空浏览器历史记录以后只显示小窗，无法正常查看。插件数据拉取没有问题。base海外。
![image](https://github.com/user-attachments/assets/6135836d-9413-4942-a10f-26bd2aead6c7)
![image](https://github.com/user-attachments/assets/f6280c91-1295-4f33-8e99-446a8b94a335)

**Comment by labuladong** [comment]
看来是思路弹窗的大小太小了。注意看弹窗右下角，可以拖动，你把弹窗拉大一些应该就正常了

<img width="731" alt="image" src="https://github.com/user-attachments/assets/6ae3704d-333b-454e-b6b5-66922720188f">


下个版本会优化一下，限制思路弹窗的 min-height, min-width，避免出现这种情况。

**Comment by Joan-gao** [comment]
ok 已经解决了 非常感谢:)
