### ISSUE TITLE
网站BUG中英文翻译混乱

### ISSUE THREAD

**Issue by dev-seahouse** [labuladong/fucking-algorithm#1616]
**Version:**
What's the extension version are you using?
5.0.4
**Describe the bug**
https://labuladong.online/algo/data-structure/reverse-linked-list-recursion/
**Screenshots**

**Platform**
Mobile phone or PC?
What kind of web browser? (chrome/edge/...)

**Comment by labuladong** [comment]
https://labuladong.online/algo/data-structure/reverse-linked-list-recursion/
我没看出这个链接有什么问题？

**Comment by labuladong** [comment]
如果你说的是英文版 https://labuladong.online/algo/en/data-structure/reverse-linked-list-recursion/，目前处于刚上线阶段，翻译确实不是很完善，后续会逐步优化的
