### ISSUE TITLE
Website repeatedly ask  to switch language

### ISSUE THREAD

**Issue by George614** [labuladong/fucking-algorithm#1617]
我是一个国外的中文用户，平时系统语言是英文但是读labuladong的文章用中文。最近网站每打开一个tab就提示我要切换到英文，不会记住我的选择，非常影响用户体验，希望能修改一下, 谢谢。btw, 我用的Brave浏览器。

祝好，

**Comment by labuladong** [comment]
收到，我看下这个问题

**Comment by labuladong** [comment]
已复现，确实存在这个问题，我会修复一下，感谢反馈~

**Comment by labuladong** [comment]
感谢反馈，已修复此问题
