### ISSUE TITLE
chrome dev版本插件不能使用

### ISSUE THREAD

**Issue by cycai0312** [labuladong/fucking-algorithm#1618]
**Describe the bug**
插件显示未连接，LeetCode也不能看思路

控制台报错如下：
Refused to load the script 'chrome-extension://d7a9b7ed-daa3-47a7-a3b6-13ed070416f3/assets/chunk-cbcd1278.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Screenshots**
![image](https://github.com/user-attachments/assets/86c9ad86-1d85-434c-a1ea-841c6e08200b)

**Platform**
What kind of web browser are you using? (chrome/edge/...)
chrome dev
Version 131.0.6738.0 (Official Build) dev (64-bit)

**Comment by labuladong** [comment]
已复现，dev 版本确实有这个问题，我会着手修复。

现在可以有两种解决方案：
1、暂时使用 vscode/Jetbrain 插件，等待新版 Chrome 插件发布修复此问题。
2、使用正式版 Chrome，目前没有这个问题。

**Comment by labuladong** [comment]
v5.0.5 chrome 插件已修复 dev 版本无法使用的问题，请更新版本
https://chromewebstore.google.com/detail/elafhogmnaapleckojedgipgmidneccg
