### ISSUE TITLE
vscode 的插件失去新功能，与原版的leetcode插件一样了

### ISSUE THREAD

**Issue by Tendo33** [labuladong/fucking-algorithm#1619]
**Version:**
What's the extension version are you using?
最新

**Describe the bug**
没有解题思路以及网页跳转了，之前TEST操作按钮旁边是有思路解释的

**Screenshots**
![image](https://github.com/user-attachments/assets/7f25cef0-3919-4af6-b3e6-07f4a56ab3f1)

**Comment by labuladong** [comment]
手动刷新数据试一下呢

**Comment by Tendo33** [comment]
> 手动刷新数据试一下呢

是要卸载重新安装吗

**Comment by labuladong** [comment]
按 F1，搜索 手动刷新 labuladong 数据 的选项，点击，就可以手动触发数据拉取，应该就能解决你的问题了
