### ISSUE TITLE
请求题解代码添加Rust语言版本

### ISSUE THREAD

**Issue by InfyniteHeap** [labuladong/fucking-algorithm#1620]
简要解释下我提出这个建议的原因：
1. Rust正变得越来越流行，然而市面上关于Rust算法讲解的资源却寥寥无几。
2. 其他语言中的合法写法在Rust中可能是非法的，因此部分题目使用Rust解答时可能会更加困难（例如解答链表和二叉树等与指针有关的题目）。

我是一名普通Rust学习者，最近也正在通过本网站学习解题技巧。对我来说，将部分题目的现有题解代码翻译成Rust可能会比较困难。因此，我想请求网站的题解代码添加Rust语言版本，这样后面的Rust初学者想通过本网站学习解题技巧及刷算法题就会相对轻松一些了。

我真的很喜欢这个网站，我也从中受益匪浅。希望东哥可以考虑一下我的这条小小建议！

**Comment by labuladong** [comment]
我学过 rust 的一点皮毛，和其他语言相比，它实现数据结构确实需要特殊的技巧。

对 rust 的支持我会做的，争取做到大家学完算法还能学会 rust。只是这个事情优先级会比较靠后，毕竟目前 rust 玩家相比其他语言是少数。

不过你可以在学习网站时尝试用 rust 来实现，并把代码评论一下，一方面促使自己动手实践，另一方面也可以给其他 rust 读者以及我未来的工作提供一些帮助。

谢谢你的建议，如果你有更多想法，欢迎分享~

**Comment by InfyniteHeap** [comment]
> 我学过 rust 的一点皮毛，和其他语言相比，它实现数据结构确实需要特殊的技巧。
> 
> 对 rust 的支持我会做的，争取做到大家学完算法还能学会 rust。只是这个事情优先级会比较靠后，毕竟目前 rust 玩家相比其他语言是少数。
> 
> 不过你可以在学习网站时尝试用 rust 来实现，并把代码评论一下，一方面促使自己动手实践，另一方面也可以给其他 rust 读者以及我未来的工作提供一些帮助。
> 
> 谢谢你的建议，如果你有更多想法，欢迎分享~

好的，感谢东哥！
