### ISSUE TITLE
如何选择生成文件的语言？

### ISSUE THREAD

**Issue by Tendo33** [labuladong/fucking-algorithm#1621]
**Version:**
最新版本
**Describe the bug**

因为之前一直在使用，所有生成的文件名都是中文的，更新之后重新打开问题会出现一个新的英文名称的文件，所以相同的问题会重复
在setting中也没有找到相关的设置

**Screenshots**
![image](https://github.com/user-attachments/assets/e4fab35d-2c57-49da-9aaf-2130e2bb9b33)

**Comment by labuladong** [comment]
谢谢反馈，文档没写清楚。如下图，按照语言进行设置，你想要的应该是 `${id}.${cn_name}.${ext}`
<img width="960" alt="image" src="https://github.com/user-attachments/assets/6582607f-629c-4672-b506-7a2dc49613fa">
<img width="574" alt="image" src="https://github.com/user-attachments/assets/00877ecb-b4ff-472f-8932-e4b3c9ecbf13">

**Comment by Neverland3124** [comment]
东哥你好  可以考虑把 `${cn_name}` 加到网站的可用的变量版块里 我也是找到这里才知道的

**Comment by labuladong** [comment]
> 网站的可用的变量版块里

你是指 `${code}` 那个吗？

**Comment by Neverland3124** [comment]
> > 网站的可用的变量版块里
> 
> 你是指 `${code}` 那个吗？

这个板块 - [设置代码文件的名字和路径？](https://labuladong.online/algo/intro/vscode/#%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%A0%81%E6%96%87%E4%BB%B6%E7%9A%84%E5%90%8D%E5%AD%97%E5%92%8C%E8%B7%AF%E5%BE%84)

**Comment by labuladong** [comment]
本来就是有的，设置那个 name 就可以，可以根据 力扣/LeetCode 自动设置中英文题目为文件名。
