### ISSUE TITLE
设置代码文件的名字

### ISSUE THREAD

**Issue by 7ywx** [labuladong/fucking-algorithm#1623]
原来代码文件为题目的中文名字
更新之后变成了英文，怎么变回英文

**Comment by labuladong** [comment]
版本号是多少

**Comment by labuladong** [comment]
https://github.com/labuladong/fucking-algorithm/issues/1621

**Comment by 7ywx** [comment]
2.0.1
![image](https://github.com/user-attachments/assets/0af7db9c-bef9-4788-9524-1fafea8d7743)

**Comment by labuladong** [comment]
解法见 https://github.com/labuladong/fucking-algorithm/issues/1621
