### ISSUE TITLE
idea插件无法登陆

### ISSUE THREAD

**Issue by ChidoriZZ** [labuladong/fucking-algorithm#1624]
**Version:**
What's the plugin version are you using?
IDEA版本2023.1.5，插件版本2.0.1

**Describe the bug**
无法进行登陆，清除插件缓存、降插件版本、清除IDEA缓存都无效。按照文档的操作进行插件的配置，点击OK之后没有弹出让我配置cookie的弹窗，也没看到其他可以配置登陆信息的地方

**Screenshots**
<img width="694" alt="image" src="https://github.com/user-attachments/assets/ac7ab681-1826-47cb-bffd-ea14cdd412a6">
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/ec388932-9831-4ea6-a8e7-2a3720ae0ef8">

**Comment by labuladong** [comment]
谢谢反馈问题，按理说不应该弹出这个错误。似乎没有其他读者反馈这个问题，我本地也没复现出来，不知道为什么你会出现这个问题。

不过我根据你的描述尝试优化了一下可能出问题的地方，发布了新版 v2.0.2，预计两天内审核上架，上架后我会在这里更新状态，届时请你更新后尝试。

目前可以暂时使用 vscode/Chrome 插件。

**Comment by labuladong** [comment]
https://plugins.jetbrains.com/plugin/19317-leetcode-with-labuladong/versions/stable/618621
v2.0.2 已发布，请更新后尝试是否解决问题？

**Comment by ChidoriZZ** [comment]
已经可以了，谢谢东哥

**Comment by labuladong** [comment]
那就好，后续遇到任何问题随时反馈，感谢 :)
