### ISSUE TITLE
代码模板怎么使用

### ISSUE THREAD

**Issue by 7ywx** [labuladong/fucking-algorithm#1625]
**Version:**
最新版本

**Describe the bug**
代码模板怎么使用

**Screenshots**
![image](https://github.com/user-attachments/assets/548b243e-798a-421f-a380-69b9238fa04b)
![image](https://github.com/user-attachments/assets/f0b7c918-71b7-485e-b037-ea2bf584113a)

**Comment by labuladong** [comment]
你配置上之后打开代码文件就会自动把 ${code} 部分替换成题目代码

**Comment by 7ywx** [comment]
加在了这
![image](https://github.com/user-attachments/assets/9fa2d447-cd27-4c91-8291-0b29fd7c92b8)

想加在这咋整
![image](https://github.com/user-attachments/assets/4be62c89-3ecf-4998-8126-c17f4a64bcc1)
