### ISSUE TITLE
内容不能显示英文

### ISSUE THREAD

**Issue by wenwen-flower** [labuladong/fucking-algorithm#1627]
**Version:**
What's the plugin version are you using?
2.0.2
**Describe the bug**
语言已经设置为英语但是，内容显示还是中文
**Screenshots**
![image](https://github.com/user-attachments/assets/42a72033-2df4-4385-bbd2-96199f563740)

**Comment by labuladong** [comment]
想要英文题目，你应该修改 website 为 leetcode.com，而不是语言选项

**Comment by wenwen-flower** [comment]
可是浏览器上登录leetcode.cn可以设置英文内容， 原插件也是可以的

**Comment by labuladong** [comment]
嗯，这个目前确实还没支持，你先暂时用着吧，下个版本可以支持一下
