### ISSUE TITLE
translate +动态规划系列/动态规划之博弈问题

### ISSUE THREAD

**Issue by wadegrc** [labuladong/fucking-algorithm#17]
我将开始翻译如下文章（点击可查看目标文章）：

[动态规划系列/动态规划之博弈问题.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E4%B9%8B%E5%8D%9A%E5%BC%88%E9%97%AE%E9%A2%98.md)

我准备将它翻译成：**英文**

**预计 7天内翻译完成**，若由于种种原因没有完成，如果你愿意，你可以接替我的工作翻译这篇文章。

**Comment by labuladong** [comment]
2020/3/1 update: 由于需要借助 Github Trending 推荐这波曝光，英文版需快速完成，所以更改之前的计划，任务不再具有抢占性，issue 中申明的时间不再有效，**主仓库会接受最先提交 pull request 的文章，认定提交者为翻译者，并且会在开头声明翻译者及其链接**。

请注意你的工作是否被其他人完成，详情见 [置顶 issue](https://github.com/labuladong/fucking-algorithm/issues/9)
