### ISSUE TITLE
每次登录都会弹出“Faield to fetch today question”错误提示

### ISSUE THREAD

**Issue by lmmorghulis** [labuladong/fucking-algorithm#1739]
**Version:**
v2.0.2

**Describe the bug**
每次打开vscode登录leetcode插件后右下角都会出现此弹窗提示（但实际上“每日一题”是能正常显示的），即使在vscode设置中选择“关闭该插件所有通知”也依然会弹出。

**Screenshots**
![QQ图片20241031213853](https://github.com/user-attachments/assets/a1ad1098-3d74-40d8-a560-2afd5afd9907)

**Comment by labuladong** [comment]
谢谢反馈，确实有这个问题，下个版本修复

**Comment by labuladong** [comment]
v2.0.3 已发布，修复了这个问题，请尝试更新最新版本。
