### ISSUE TITLE
VSCode 在 test case 注释前面自动添加 `*`

### ISSUE THREAD

**Issue by lmmorghulis** [labuladong/fucking-algorithm#1740]
**Version:**
v2.0.2

**Describe the bug**
点击“RunTest”或“RunAllTests”后插件并不能正常地运行测试，似乎是由于把前面的注释符也当作了输入内容，在各道题目中该问题普遍存在。

**Screenshots**
![Snipaste_1031_21-50-15](https://github.com/user-attachments/assets/50815f84-ed85-4f5e-834b-ddd1be2b15d0)
![Snipaste_1031_21-50-31](https://github.com/user-attachments/assets/72059b88-ef03-47e4-ac63-31bc39c816aa)

**Comment by labuladong** [comment]
为什么会出现你这种形式的注释呢？是手动添加的吗？

我试了下，自动生成的测试用例应该是这种格式，不会带前缀 `*`:

<img width="386" alt="image" src="https://github.com/user-attachments/assets/c11d4f4f-d390-451a-a4ab-d1204f370c03">

**Comment by lmmorghulis** [comment]
知道了！原来是VSCode将注释也给自动格式化了造成的，我把下面这个选项取消勾选就行了，感谢！
![image](https://github.com/user-attachments/assets/f49d315d-405a-4f63-8a2c-ba77dbafa4c9)

**Comment by labuladong** [comment]
怪不得，我没有给 vscode 配置 Java。原来还有这个坑，谢谢反馈解决方案~
