### ISSUE TITLE
中国站无法登陆，国际站则超时

### ISSUE THREAD

**Issue by bertcai** [labuladong/fucking-algorithm#1825]
**Version:**
v2.0.2

**Describe the bug**
中国站登陆失败
国际站则超时
终端curl均有返回

**Screenshots**
![image](https://github.com/user-attachments/assets/aab2a43e-8643-45bd-88b5-3bb9ec53dc60)
![image](https://github.com/user-attachments/assets/713b725f-fc28-4ea2-b4a5-fbd2c6272e74)

**Comment by labuladong** [comment]
用的啥浏览器，是不是 chrome/Edge？

**Comment by labuladong** [comment]
有的读者用 arc 浏览器，复制的 curl 命令有 Bug，会导致类似的问题。所以如果你用的非 Chrome/Edge 浏览器，建议先用这些主流浏览器试下，是否还有问题。

**Comment by bertcai** [comment]
我用的chrome浏览器和edge都试了，我觉得是这个
https://leetcode.cn/problemset/这个地址现在不行了，大陆站的这个地址现在是个304

**Comment by labuladong** [comment]
我本地也复现了这个问题，我会尽快修复，谢谢反馈。目前可以先使用其他插件。

**Comment by labuladong** [comment]
v2.0.3 已发布，修复了这个问题，请尝试更新最新版本。
