### ISSUE TITLE
招聘贴：阿里巴巴消息业务/基础团队招聘（校招/社招）

### ISSUE THREAD

**Issue by hepin1989** [labuladong/fucking-algorithm#192]
我自己的小团队都是Java哈，也有cpp、ios和android，欢迎大家加入。
招聘, 微信：kerisle，
大家也可以直接发邮件
hepin.p@alibaba-inc.com
![image](https://user-images.githubusercontent.com/501740/76192722-7a152080-621d-11ea-8197-6569185c1092.png)

**Comment by OhIAmFine** [comment]
你们是写了脚本来发这种 issue 了吧，说实话有点违背 github 精神了吧，属实有点恶心了吧 @hepin1989

**Comment by hepin1989** [comment]
不是。。。我是手动发的，我只选了几个比较好的发了下。

**Comment by labuladong** [comment]
这广告太狠了，要是真的求贤若渴，就请帮我和楼上老铁内推进阿里【手动滑稽】 @hepin1989

**Comment by hepin1989** [comment]
@OhIAmFine @labuladong 简历. hepin.p#alibaba-inc.com

**Comment by MarsZone** [comment]
阿里你们真的够了，到处招人其实是背的KPI。。其实根本不缺人。

**Comment by hepin1989** [comment]
真的确人。。。已经忙不过来了。我们应用多。

**Comment by fgheng** [comment]
> 真的确人。。。已经忙不过来了。我们应用多。

不会java进去现学可行么？

**Comment by hepin1989** [comment]
> 不会java进去现学可行么？
还有别的岗位，数据、客户端也可以的，您看看呢？算法好也可以的。https://github.com/CampusCenter/JobBoard/issues/1

**Comment by fgheng** [comment]
> > 不会java进去现学可行么？
> > 还有别的岗位，数据、客户端也可以的，您看看呢？算法好也可以的。[CampusCenter/JobBoard#1](https://github.com/CampusCenter/JobBoard/issues/1)
感谢

**Comment by chufulong** [comment]
真有你的！

**Comment by SilenceHS** [comment]
没有前端。。我走了😭

**Comment by hepin1989** [comment]
> 没有前端。。我走了😭

我们准备支持消息的JS-SDK的

**Comment by yangyang-zhang** [comment]
我想进去跟大佬学习~~
