### ISSUE TITLE
Bug of formula presentation

### ISSUE THREAD

**Issue by tommytim0515** [labuladong/fucking-algorithm#200]
![Screenshot (337)](https://user-images.githubusercontent.com/44408451/76272845-5acad180-62b7-11ea-92e4-855d21abeb7e.png)

你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[高频面试系列/一行代码解决的智力题.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97/%E4%B8%80%E8%A1%8C%E4%BB%A3%E7%A0%81%E8%A7%A3%E5%86%B3%E7%9A%84%E6%99%BA%E5%8A%9B%E9%A2%98.md)

问题描述：

The mathematical formula cannot be presented correctly with Latex notation in markdown files.

**Comment by labuladong** [comment]
Fixed.

**Comment by tommytim0515** [comment]
Please also fix the English version. Thanks!

**Comment by labuladong** [comment]
My fault, done.
