### ISSUE TITLE
ProblemS

### ISSUE THREAD

**Issue by sunningilyA7** [labuladong/fucking-algorithm#2065]
<img width="841" alt="problems2" src="https://github.com/user-attachments/assets/aaedb7e1-00b9-43ce-a0d5-677c33102ecb">
**Version:**
What's the extension version are you using?
不能使用【思路】 显示需要登录

**Describe the bug**
插件页面- 新版网站会员显示X

**Screenshots**
<img width="841" alt="problems1" src="https://github.com/user-attachments/assets/e60aaa23-5020-4b40-a571-ad7eac8dd74a">

**Platform**
Mobile phone or PC?
What kind of web browser? (chrome/edge/...)
mac chrome

**Comment by labuladong** [comment]
若你未购买网站会员，请购买。

若你已购买，请参照 [网站会员](https://labuladong.online/algo/intro/site-vip/) 下方的解锁方法，点击「手动刷新数据」按钮，应该就不会显示 X 了。
