### ISSUE TITLE
idea插件中的leetcode官方题解中md语法未能正常显示

### ISSUE THREAD

**Issue by zwjtfd** [labuladong/fucking-algorithm#2088]
**Version:**
What's the plugin version are you using?
2.0.2
**Describe the bug**
idea插件中的leetcode官方题解中md语法未能正常显示。但是对比最新版本8.14的leetcode editor是可以正常显示的
**Screenshots**
![image](https://github.com/user-attachments/assets/e5db0782-204f-4215-aab6-c4b7dd4fab9f)
![image](https://github.com/user-attachments/assets/82ffba78-5cb8-4cf4-8fd5-9bd1d1235bb8)

**Comment by labuladong** [comment]
收到，已复现，下个版本修复

**Comment by labuladong** [comment]
v2.0.3 修复了这个问题，请更新
