### ISSUE TITLE
仓库可以改个名字吗

### ISSUE THREAD

**Issue by tenvgo** [labuladong/fucking-algorithm#214]
比如叫做cracking-algorithm，现在的这个词，不爱说脏话的人就不太想看到这个词，受众范围变小了

**Comment by eyea** [comment]
宋小宝那么黑，咋不让他重新投胎下呢，不喝孟婆汤那种？
看内在，学思维方式，学逻辑套路。
讲真，这个提issue就很有趣，更有趣的是，我还跟帖了。
建议关闭。

**Comment by labuladong** [comment]
现在的这个词，我们替不爱说脏话的人说出了这个词，潜在的受众范围变大了。
名字受之于作者的一拍脑袋，是该仓库立于天地之本。
它的名字已经刻入了 URL，被无数网站所引用，让他们全部变成 404 Not Found，你于心何忍呢？
讲真，这个提issue就很有趣，更有趣的是，我还回复了。
已经置顶。

**Comment by huanghe2015** [comment]
脏话和文明之间没有必然的关系。不希望政治正确在这里出现。

**Comment by GaoXinLXL** [comment]
正是这个F开头的词，让我深深记住了它

**Comment by KOPFYF** [comment]
xswl

**Comment by TheBadZhang** [comment]
shit-algorithm？

**Comment by GengchenXU** [comment]
本来再力扣刷题看见作者，一天手贱在gayhub搜了fuck哈哈哈

**Comment by labuladong** [comment]
GitHub 蹭星星大法：名字起的好，star 少不了🤣

**Comment by 0x2CA** [comment]
暴躁老哥在线讲解🤣

**Comment by gantrol** [comment]
取cracking-algorithm的话，我现在就找不回这个仓库了。。

**Comment by GreenGums** [comment]
> 正是这个F开头的词，让我深深记住了它

f**k

**Comment by Asaki-byte** [comment]
阿巴阿巴阿巴阿巴阿巴

**Comment by abowloflrf** [comment]
尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。

**Comment by labuladong** [comment]
@abowloflrf 如果改名字，**所有链接到这个仓库的 URL 都会 404，这个仓库就会失去流量**。这个现实的理由，可以驳回一切文绉绉的争论。我只尊重现实，不尊重正确，少动嘴，多动手，这才是一个工程师最基本的素质。

**Comment by pusidun** [comment]
我第一眼看到这个repo，就想到一个LICENSE叫WTFPL，感觉很有趣

**Comment by songquanpeng** [comment]
不会 404 ，Github 会自动重定向的

**Comment by xinrong2019** [comment]
有意思

**Comment by 94rain** [comment]
改名之后确实是会自动重定向的

**Comment by sekfung** [comment]
Read the fucking source code!!! --Linus Torvalds

**Comment by oldthreefeng** [comment]
开头启动好，星星少不了。 

fucking-algorithm ~~~~

**Comment by Sunzheng-Hub** [comment]
y1s1 最开始确实是这个名字吸引我的😏

**Comment by dukeNashor** [comment]
> 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。

+1

**Comment by bot66** [comment]
我觉得8行

**Comment by xitish** [comment]
asd

**Comment by xitish** [comment]
asd

**Comment by yydzxz** [comment]
> 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。

![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
不知道国人这个友邦惊诧的习惯什么时候才能改过来

**Comment by Orocker** [comment]
awsl

**Comment by mugudamowang** [comment]
从作者的角度出发, 花费这么大精力来做这个公益性事情, 反而在几乎无关的事实上被吐槽我觉得是非常........不说了我刷题去了

**Comment by YeHaijia** [comment]
宁就是大圣人？来,楼主也开一个56kstar的holy-algorithm

**Comment by ZHANG-Zhilong** [comment]
人家爱改名改名，不爱改名就不该。怎么就那么多事。嫌弃名字不好，你自己起一个项目啊，别用人家的项目。碍着你了是咋的了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: mugudamowang<mailto:notifications@github.com>
发送时间: 2020年8月19日 11:20
收件人: labuladong/fucking-algorithm<mailto:fucking-algorithm@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [labuladong/fucking-algorithm] 仓库可以改个名字吗 (#214)


从作者的角度出发, 花费这么大精力来做这个公益性事情, 反而在几乎无关的事实上被吐槽我觉得是非常........不说了我刷题去了

―

**Comment by bot66** [comment]
> > 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。
> 
> ![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
> 不知道国人这个友邦惊诧的习惯什么时候才能改过来. 人家英语为母语的人玩f**k玩得挺嗨, 都上License列表了

参考[darknet库](https://github.com/pjreddie/darknet)，直接“LICENSE.fuck”。

**Comment by winteroo** [comment]
有意思的提问

**Comment by xushuosean** [comment]
别人是来看项目，我是来听相声的

**Comment by lusuzi** [comment]
fuck这词很好啊，它是少有的可以用其三个不同词性组成一个句子的词，为什么要换？

**Comment by lusuzi** [comment]
> fuck这词很好啊，它是少有的可以用其三个不同词性组成一个句子的词，为什么要换？

fuck fucking fucker!

**Comment by Ninesss** [comment]
名字什么的，真不用纠结太多；）

**Comment by ilp2020** [comment]
> > > 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
> > 不知道国人这个友邦惊诧的习惯什么时候才能改过来. 人家英语为母语的人玩f**k玩得挺嗨, 都上License列表了
> 
> 参考[darknet库](https://github.com/pjreddie/darknet)，直接“LICENSE.fuck”。

如果你觉得license是不好的东西，你会用某个词来表达对它的看法。但是如果你认为算法是优秀的好的东西，很美好的东西，你会去认真学习的东西，为什么要用这个词来表达对它的看法

**Comment by Hellcatzm** [comment]
> > > > 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
> > > 不知道国人这个友邦惊诧的习惯什么时候才能改过来. 人家英语为母语的人玩f**k玩得挺嗨, 都上License列表了
> > 
> > 
> > 参考[darknet库](https://github.com/pjreddie/darknet)，直接“LICENSE.fuck”。
> 
> 如果你觉得license是不好的东西，你会用某个词来表达对它的看法。但是如果你认为算法是优秀的好的东西，很美好的东西，你会去认真学习的东西，为什么要用这个词来表达对它的看法



> > > > 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
> > > 不知道国人这个友邦惊诧的习惯什么时候才能改过来. 人家英语为母语的人玩f**k玩得挺嗨, 都上License列表了
> > 
> > 
> > 参考[darknet库](https://github.com/pjreddie/darknet)，直接“LICENSE.fuck”。
> 
> 如果你觉得license是不好的东西，你会用某个词来表达对它的看法。但是如果你认为算法是优秀的好的东西，很美好的东西，你会去认真学习的东西，为什么要用这个词来表达对它的看法

对算法这么深情表白的浪漫场景我都不好意思回复了，但我还是要是说不要因为项目名字这种破事刷楼了，关注项目的人是会收到邮件的，请把我的邮件列表留给更多有意义的邮件吧

**Comment by Hellcatzm** [comment]
> > > > > 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
> > > > 不知道国人这个友邦惊诧的习惯什么时候才能改过来. 人家英语为母语的人玩f**k玩得挺嗨, 都上License列表了
> > > 
> > > 
> > > 参考[darknet库](https://github.com/pjreddie/darknet)，直接“LICENSE.fuck”。
> > 
> > 
> > 如果你觉得license是不好的东西，你会用某个词来表达对它的看法。但是如果你认为算法是优秀的好的东西，很美好的东西，你会去认真学习的东西，为什么要用这个词来表达对它的看法
> 
> > > > > 尊重作者的意见，但是同时表达下自己的想法，也好让楼主知道并不只有自己是这么想的吧。个人也觉得看到这个词出现在仓库标题里还是有点不适的，尤其是当看到出现在trending首页和其他严肃优秀的工程项目并列在一起的时候，也不知道英语为母语的其他国外友人看到会怎么想。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/13087806/90494177-ccb41a80-e175-11ea-8d3a-36404adaf46c.png)
> > > > 不知道国人这个友邦惊诧的习惯什么时候才能改过来. 人家英语为母语的人玩f**k玩得挺嗨, 都上License列表了
> > > 
> > > 
> > > 参考[darknet库](https://github.com/pjreddie/darknet)，直接“LICENSE.fuck”。
> > 
> > 
> > 如果你觉得license是不好的东西，你会用某个词来表达对它的看法。但是如果你认为算法是优秀的好的东西，很美好的东西，你会去认真学习的东西，为什么要用这个词来表达对它的看法
> 
> 对算法这么深情表白的浪漫场景我都不好意思回复了，但我还是要是说不要因为项目名字这种破事刷楼了，关注项目的人是会收到邮件的，请把我的邮件列表留给更多有意义的邮件吧

以及外国人看了怎么想管我毛事？

**Comment by JerryAllison** [comment]
外国友人有中文这么好的吗？

------------
Best Regards
Leo


叠加态的猫 <notifications@github.com> 于2020年11月26日周四 下午9:09写道：

**Comment by Hwloser** [comment]
一个名字罢了，内容才会重要一些

**Comment by shihuaxing** [comment]
就是因为这个词, 我才点的star. 表达了作者对形式主义和现实的控诉, 以及放荡不羁的性格.

**Comment by awesomele** [comment]
暴躁创业团队整天都是各种f。超喜欢这个名字！

**Comment by Jiangsissi720** [comment]
有这时间关心叫什么名字 多做几道题好不好 本来就是作者造福大家的事情 爱起什么名字就什么名字 这个仓库又不是专门给外国人看的 爱叫啥叫啥

**Comment by labuladong** [comment]
@Jiangsissi720 是个明白人
