### ISSUE TITLE
算法思维--滑动窗口抽象思想

### ISSUE THREAD

**Issue by markman101** [labuladong/fucking-algorithm#215]
int left = 0, right = 0;

while (right < s.size()) {
    window.add(s[right]);
    right++;
    
    while (valid) {
        window.remove(s[left]);
        left++;
    }
}
这里valid 容易让人迷惑。
while (valid)如果描述为：
1 在可行解中选择最优解
2 在非可行解中通过left++的方式寻找可行解
个人感觉更清晰

**Comment by labuladong** [comment]
好的，公众号重写了一篇更详细的进阶版
