### ISSUE TITLE
二分查找详解的一个优化小建议

### ISSUE THREAD

**Issue by littlebeast0** [labuladong/fucking-algorithm#222]
在[二分查找详解](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE%E8%AF%A6%E8%A7%A3.md)
这篇文章中，寻找左侧边界二分查找left_bound和右侧边界二分查找right_bound的函数里，都有一段数组越界检查代码。
分别如下：
```java
int left_bound(int[] nums, int target) {
	// ...
    // 最后要检查 left 越界的情况
    if (left >= nums.length || nums[left] != target)
        return -1;
    return left;
}
```

```java
int right_bound(int[] nums, int target) {
    // ...
    // 最后要检查 right 越界的情况
    if (right < 0 || nums[right] != target)
        return -1;
    return right;
}
```
楼主的这两段代码本意应该是对数组index的越界情况进行检查。
最后统一写成下面这样子会不会更好一些呢？
```java
    if (right < 0 || left >= nums.length)
        return -1;
```
这样子left_bound和right_bound函数的只需要在
```java
if ( nums[mid] == target ) {
  // 
}
```
和尾部的return句子稍加修改即可。

**Comment by labuladong** [comment]
这个想法好，我去测试一下！

**Comment by xiaohangcd** [comment]
> 在[二分查找详解](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE%E8%AF%A6%E8%A7%A3.md)
> 这篇文章中，寻找左侧边界二分查找left_bound和右侧边界二分查找right_bound的函数里，都有一段数组越界检查代码。
> 分别如下：
> 
> ```java
> int left_bound(int[] nums, int target) {
> 	// ...
>     // 最后要检查 left 越界的情况
>     if (left >= nums.length || nums[left] != target)
>         return -1;
>     return left;
> }
> ```
> 
> ```java
> int right_bound(int[] nums, int target) {
>     // ...
>     // 最后要检查 right 越界的情况
>     if (right < 0 || nums[right] != target)
>         return -1;
>     return right;
> }
> ```
> 
> 楼主的这两段代码本意应该是对数组index的越界情况进行检查。
> 最后统一写成下面这样子会不会更好一些呢？
> 
> ```java
>     if (right < 0 || left >= nums.length)
>         return -1;
> ```
> 
> 这样子left_bound和right_bound函数的只需要在
> 
> ```java
> if ( nums[mid] == target ) {
>   // 
> }
> ```
> 
> 和尾部的return句子稍加修改即可。
这样好像不行 可能出现一侧出界但刚刚好第0个数（或者最后一个数）是想要找的边界的情况，这么写这种情况就直接返回-1了
