### ISSUE TITLE
顯示不出思路和題解

### ISSUE THREAD

**Issue by lololso** [labuladong/fucking-algorithm#2231]
**Describe the bug**
Leetcode page can't show 思路和題解

**Screenshots**
![沒有思路和題解](https://github.com/user-attachments/assets/b9933712-2edb-4550-8b0b-1c202645485e)

**Platform**
What kind of web browser are you using? (chrome/edge/...)
edge

**Comment by labuladong** [comment]
收到，这个题的思路是有 bug，下个版本会修复

**Comment by labuladong** [comment]
v5.0.6 版本已修复这个问题
