### ISSUE TITLE
题号应该为355，非335.（fucking-algorithm/数据结构系列/设计Twitter.md）

### ISSUE THREAD

**Issue by 81981266** [labuladong/fucking-algorithm#226]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/抢房子.md](https://github.com/labuladong/fucking-algorithm/blob/master/动态规划系列/抢房子.md)

问题描述：

某章图片链接失效/其中的 XXX 内容有误/等等。

**Comment by labuladong** [comment]
好的，谢谢指出

**Comment by labuladong** [comment]
没看到有什么问题？
