### ISSUE TITLE
求文中画算法图软件

### ISSUE THREAD

**Issue by coldbath** [labuladong/fucking-algorithm#228]
请向大佬请教一下，这个画图软件是什么，感觉非常适合整理算法思路，谢谢．

**Comment by yusubond** [comment]
同问，感觉这个画图软件不错，想学习和使用，谢谢。

**Comment by labuladong** [comment]
iPad 上一款叫做 FlipaClip 的软件配合 Apple pencil 画的。你们要用的话，帮我找他们收点广告费。
