### ISSUE TITLE
文档是否会出专门的语言

### ISSUE THREAD

**Issue by issxjl2015** [labuladong/fucking-algorithm#229]

**Comment by issxjl2015** [comment]
什么鬼？居然显示不出来？

补充一下：
是否会出java版本或者CPP版本？目前文档的章节中有CPP实现的，也有java实现的，后续是否会出java版本或者CPP版本？当然现在的版本也是很不错的

**Comment by wyl0706** [comment]
出专门的语言毫无意义，算法本来就是语言无关的。就是用伪代码都很正常

**Comment by labuladong** [comment]
楼上说得对

**Comment by SchopenhauerZhang** [comment]
不过可以增加各个语言版本的例子，比如用python如何实现、c++如何实现等，比如我本地在写python和c++版本的例子，如果作者同意，后面我可以提个pr。

**Comment by SchopenhauerZhang** [comment]
手动实现的时候会意识不到文档中用的什么语言，特别是c++和java。毕竟不是所有人都了解c++和java的语法，比如我。最好能在例子代码上标注下什么语言比较好，特别是有些例子出现了java代码调用c++代码的情况。看起来会比较痛苦。毕竟算法不只是看，重要的是要能自己实现。
