### ISSUE TITLE
bug 算法思维系列/几个反直觉的概率问题.md 第一个图片错误

### ISSUE THREAD

**Issue by tobeiwanttobe** [labuladong/fucking-algorithm#231]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/几个反直觉的概率问题.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%87%A0%E4%B8%AA%E5%8F%8D%E7%9B%B4%E8%A7%89%E7%9A%84%E6%A6%82%E7%8E%87%E9%97%AE%E9%A2%98.md)

问题描述：

第一个图片有错误。

**Comment by Lyjeeq** [comment]
@tobeiwanttobe 以k分组翻转嘛，有什么错误，可以描述下嘛

**Comment by tobeiwanttobe** [comment]
> @tobeiwanttobe 以k分组翻转嘛，有什么错误，可以描述下嘛

你没有发现这个图片在这个文章中不应该存在吗?

**Comment by labuladong** [comment]
已修复，谢谢
