### ISSUE TITLE
idea点击题目名称，打不开做题的界面

### ISSUE THREAD

**Issue by Sanctyzl** [labuladong/fucking-algorithm#2324]
**Version:**
What's the plugin version are you using?
2.0.2

**Describe the bug**
idea点击题目名称，打不开做题的界面，不会生成java文件

**Screenshots**
![image](https://github.com/user-attachments/assets/5519208f-21df-4668-acdc-dc6bff79cf2a)

**Comment by labuladong** [comment]
如果是力扣会员题，若非力扣会员，是无法打开的，这是预期行为。

如果你是说所有题目都无法打开的话，那就是有 bug，但是我本地测试是正常的，并未复现你所说的问题。

**Comment by Sanctyzl** [comment]
我刚刚又试了一下，发现选中一道题后右键open question还是能打开的，但是直接双击有的题就打不开，很奇怪，因为我之前一直是双击的。不管怎样，现在可以右键打开刷题了，还是不影响正常使用。

**Comment by labuladong** [comment]
OK，暂时没有其他用户反馈这个问题，我也没有复现出来，先关闭了。后续如果能复现则修复这个问题。

**Comment by labuladong** [comment]
如果没有设置文件存储路径，也可能导致无法打开题目，设置上一个合法的路径后即可正常打开了。
![image](https://github.com/user-attachments/assets/8c7e6599-0dcb-476a-8a4c-d332afa27d64)
