### ISSUE TITLE
不显示✨标记

### ISSUE THREAD

**Issue by wenwade** [labuladong/fucking-algorithm#2325]
**Version:**
What's the extension version are you using?
vscode: 
版本: 1.91.1 (Universal)
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:07:54.982Z (4 个月前)
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 24.1.0

plugin version: v2.0.3

**Describe the bug**
没有✨标记，也不显示labuladong讲解（昨天还是好的）。手动拉取数据，在运行时状态可以看到以下信息：
Activated by onView:QuestionExplorer event: 5ms

未捕获的错误(2)
 e.extra_brief_v3 is not iterable

 e.extra_brief_v3 is not iterable

**Comment by labuladong** [comment]
我并没有复现出这个问题，猜测可能是你的网络问题，尝试换个网络或者重启呢？
