### ISSUE TITLE
手机版弹窗过窄

### ISSUE THREAD

**Issue by nowsdt** [labuladong/fucking-algorithm#2339]
![14541732681671_ pic](https://github.com/user-attachments/assets/57a9e0b5-5734-47d5-92cf-013fc3b95dd2)

手机上使用，弹窗太窄了
kiwi browser 手机浏览器，使用chrome插件

**Comment by labuladong** [comment]
拖动窗口右下角，可以调整大小

**Comment by nowsdt** [comment]
> 拖动窗口右下角，可以调整大小

ok 谢谢
