### ISSUE TITLE
设置和教程不一致

### ISSUE THREAD

**Issue by ahui66686** [labuladong/fucking-algorithm#2355]
**Version:**
What's the plugin version are you using?
最新版
**Describe the bug**
插件设置和教程中不一样，没有Customcode template
**Screenshots**
![教程](https://github.com/user-attachments/assets/fb9dd2e8-e635-4330-8e45-01c1f91f12e7)
![我的设置界面](https://github.com/user-attachments/assets/b459f5d0-64df-4e49-9d67-36bb4593269a)

**Comment by labuladong** [comment]
Customcode template 默认开启。如果你想自定义代码模板，直接修改下方 `Code Template` 中的内容即可。
