### ISSUE TITLE
Jetbrain 插件登录之后要求验证邮箱，加载题目失败 

### ISSUE THREAD

**Issue by Ggggggguy** [labuladong/fucking-algorithm#2365]
![Snipaste_2024-12-12_14-43-44](https://github.com/user-attachments/assets/b155525f-e5bb-4fc0-9ece-5b9022d6d18a)

<img width="1164" alt="Snipaste_2024-12-12_14-44-47" src="https://github.com/user-attachments/assets/55322d6f-a768-40a5-bcf7-aab98a927f1e" />

邮箱已经做了关联

**Comment by labuladong** [comment]
版本号？你估计用的旧版插件，目前最新版是 2.0.3，请更新
