### ISSUE TITLE
“如何高效寻找素数” 的优化建议

### ISSUE THREAD

**Issue by inkydragon** [labuladong/fucking-algorithm#237]
可以把 “不筛偶数，只筛奇数” 加上，这个很容易想到，比筛到 `\sqrt{n}` 和从 `i^2` 开始都更好理解。
节约内存效果也十分显著。

----

更进一步还可以用 六邻筛法（六素数法、sexy prime）步长变为 6，只用筛 6k-1、6k+1。
当然这个就不如上面那个直观易懂。可以提一下名字
至于为什么：
```
               prev(6k+5)                              next(6k-1)        next(6k+1) 
sequence: ... |6k-1|, 6k+0, |6k+1|, 6k+2, 6k+3, 6k+4, |6k+5|, 6(k+1)+0, |6(k+1)+1| ······ 
  factor:             6             2     3     2             6
```

我感觉关于算法的部分可以在末尾提一些改进算法的名字，纯文本就行，然感兴趣的人自己去搜。
就像算法复杂度一样，知道存在性还有有必要的。

**Comment by labuladong** [comment]
好建议，考虑加一下
