### ISSUE TITLE
【社招、校招】学了这么多算法不打算用到电商场景里吗？

### ISSUE THREAD

**Issue by Nerom** [labuladong/fucking-algorithm#238]
大量招人，社招校招，阿里供应链国际化团队，五新战略之首的新零售，ewtp的国际化平台，前景广阔，舞台够大，赶快来耍！！
简历请至：liuzhu.wlz#alibaba-inc.com
校招同学抓紧到碗里来，有大神指导简历，规划职业方向了，优秀的同学，可能很快就拿offer了哦

**Comment by WangAgui** [comment]
how?求指教，21届应届毕业生如何进阿里。

**Comment by Nerom** [comment]
> how?求指教，21届应届毕业生如何进阿里。

简历发到邮箱哈

**Comment by labuladong** [comment]
阿里是不是欠我一个简历？第二次跑这来招聘了  🤔

**Comment by Nerom** [comment]
> 阿里是不是欠我一个简历？第二次跑这来招聘了 🤔

大佬不来阿里试试吗？这样阿里就不欠你简历了😅
