### ISSUE TITLE
bug - 动态规划设计：最长递增子序列 - 算法bug

### ISSUE THREAD

**Issue by crackeer** [labuladong/fucking-algorithm#239]
你好，我发现**动态规划设计：最长递增子序列**如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划设计：最长递增子序列](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E8%AE%BE%E8%AE%A1%EF%BC%9A%E6%9C%80%E9%95%BF%E9%80%92%E5%A2%9E%E5%AD%90%E5%BA%8F%E5%88%97.md)

问题描述：
![image](https://user-images.githubusercontent.com/8544545/78416834-9a8a9c00-765e-11ea-9d5f-df53eba38c9d.png)
算法，在第二层循环结束之后，在进行下一次外层循环的时候，i+1 的dptable值继承i的值
```go
func fdp(list []int) []int {
	dp := []int{}
	for i := 0; i < len(list); i++ {
		dp = append(dp, 1)
	}
	for i := 0; i < len(list); i++ {
		for j := 0; j < i; j++ {
			if list[i] > list[j] {
				dp[i] = common.Max(dp[j]+1, dp[i])
			}
		}
		if i+1 < len(list) {
			dp[i+1] = dp[i]
		}
	}
	return dp
}

```

**Comment by qianyuyu** [comment]
有区别么？不更新i+1也可以跑过所有用例。
