### ISSUE TITLE
四键表达里第二个思路做了一个假设

### ISSUE THREAD

**Issue by valorliao** [labuladong/fucking-algorithm#240]
在[动态规划系列/动态规划之四键键盘.md](https://github.com/labuladong/fucking-algorithm/blob/master/动态规划系列/动态规划之四键键盘.md)， 第二个思路假设了当按键次数N比较大的时候，是A,A,A,...,A,CA,CC,CV,CV,CV,...,CV
这个情况可能更多A吧
A,A,A,...,A,CA,CC,CV,,...,CV,CA,CC,CV,...,CV

**Comment by rxyknight** [comment]
A,A,A,...(CA,CC,CV),(CA,CC,CV),(CA,CC,CV),......
N比较大的时候，每三次都会增大一倍，这个应该是最多的情况吧
