### ISSUE TITLE
优化建议：文章里面涉及的题目可以给一个跳转地址

### ISSUE THREAD

**Issue by greyireland** [labuladong/fucking-algorithm#246]
看了文章了之后，自己有思路可以根据跳转地址去刷刷题 ，这样加深理解。不然只看题目，可能效果不好！

根据大佬的文章，自己也简单总结了一下自己的刷题路程

[https://github.com/greyireland/algorithm-pattern](https://github.com/greyireland/algorithm-pattern)，有帮助的话，可以点一下关注呀😁~

就是因为题目后面没有练习题目~

我特意还在最后加了题目链接，方便练习~

广告无处不在😂~

**Comment by labuladong** [comment]
可 🤔

**Comment by mybluedog24** [comment]
同意，希望可以给出链接或者题号方便查找。正在看“滑动窗口解题套路框架”，想自己先做做看，找了很久才发现第二题已经不是easy而是medium了:satisfied:

https://leetcode.com/problems/find-all-anagrams-in-a-string/

**Comment by iamxpy** [comment]
@labuladong 同求加上题目链接！

**Comment by labuladong** [comment]
在我的 GitBook 上都加上了题目链接，且会更新最新文章：https://labuladong.gitbook.io/algo/

**Comment by greyireland** [comment]
根据大佬的文章，自己也简单总结了一下自己的刷题路程

[https://github.com/greyireland/algorithm-pattern](https://github.com/greyireland/algorithm-pattern)，有帮助的话，可以点一下关注呀😁~

就是因为题目后面没有练习题目~

我特意还在最后加了题目链接，方便练习~
