### ISSUE TITLE
translate 数据结构系列/学习算法和刷题的思路指南.md

### ISSUE THREAD

**Issue by chixinn** [labuladong/fucking-algorithm#25]
我将开始翻译如下文章（点击可查看目标文章）：

[数据结构系列/学习算法和刷题的思路指南.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%AD%A6%E4%B9%A0%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%92%8C%E7%AE%97%E6%B3%95%E7%9A%84%E9%AB%98%E6%95%88%E6%96%B9%E6%B3%95.md)

我准备将它翻译成：**英文**

**预计 10 天内翻译完成**，若由于种种原因没有完成，如果你愿意，你可以接替我的工作翻译这篇文章。

**Comment by labuladong** [comment]
2020/3/1 update: 由于需要借助 Github Trending 推荐这波曝光，英文版需快速完成，所以更改之前的计划，任务不再具有抢占性，issue 中申明的时间不再有效，**主仓库会接受最先提交 pull request 的文章，认定提交者为翻译者，并且会在开头声明翻译者及其链接**。

请注意你的工作是否被其他人完成，详情见 [置顶 issue](https://github.com/labuladong/fucking-algorithm/issues/9)
