### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by gaomingnudt** [labuladong/fucking-algorithm#252]
你好，算法思维部分->[几个反直觉的概率问题](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%87%A0%E4%B8%AA%E5%8F%8D%E7%9B%B4%E8%A7%89%E7%9A%84%E6%A6%82%E7%8E%87%E9%97%AE%E9%A2%98.md)
中的生日问题的图贴错了，帖成了反转链表的图，我猜应该是帖概率计算公式的图吧。

**Comment by labuladong** [comment]
是的，已修复，谢谢指出
