### ISSUE TITLE
按照什么顺序学习好呢？章节顺序吗

### ISSUE THREAD

**Issue by liushuikong** [labuladong/fucking-algorithm#256]
按照什么顺序学习好呢？章节顺序吗>

**Comment by labuladong** [comment]
七天过去了，你有答案了吗？

**Comment by saikei** [comment]
有点像那种不懂游泳的，一头扎进去就知道了，但在岸上永远不敢下水的永远学不会？

**Comment by XXS122** [comment]
哈哈哈&nbsp; 我也不知道怎么回事，，加个微信啊，第一次和别人在邮箱聊天挺有意思，hyj13796002437





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"saikei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:51
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] 按照什么顺序学习好呢？章节顺序吗 (#256)





 
有点像那种不懂游泳的，一头扎进去就知道了，但在岸上永远不敢下水的永远学不会？
