### ISSUE TITLE
关于股票问题，交易次数K的描述。

### ISSUE THREAD

**Issue by KaniuBillows** [labuladong/fucking-algorithm#262]
原文在提到状态转移的时候对K的描述：”如果 buy，就要从利润中减去 prices[i]，如果 sell，就要给利润增加 prices[i]。今天的最大利润就是这两种可能选择中较大的那个。而且注意 k 的限制，我们在选择 buy 的时候，把 k 减小了 1“

这个说法最初给我造成了一些误解，认为dp[i][k][1] 表示第i天的时候，还剩下k次交易次数可用。所以买入就将K-1。
但实际不是这样的。

K在前文穷举框架中提到，“比如说 dp[3][2][1] 的含义就是：今天是第三天，我现在手上持有着股票，至今最多进行 2 次交易”。
K为至今为止，已经至多进行了多少次交易。

由此在第五题
`dp[i][k][1] = Math.max(dp[i-1][k][1], dp[i-1][k-1][0] - prices[i]);`
应该如此解释：今天是第i天，当前最多进行了K次交易，当前我持有股票。
如果昨天选择了买入，对应的情况是：在第i-1天，最多进行了K-1次交易的情况下，我没有持有股票，并选择了买入，次数进行的交易次数K+1。

希望能帮到和我一样产生了困惑的人

**Comment by RPaul3** [comment]
正在发愁这个问题 感谢解答

**Comment by GreenGums** [comment]
> 这个说法最初给我造成了一些误解，认为dp[i][k][1] 表示第i天的时候，还剩下k次交易次数可用。所以买入就将K-1。

我其实还是没明白你后面对K的解释，我到现在还是理解K为剩下的交易次数。
然后我自己本人在看这类问题是，一直有一个疑问：为什么交易次数K可以和天数、是否持有股票一样进行穷举？
`    dp[i][k][0] = Math.max(dp[i-1][k][0], dp[i-1][k][1] + prices[i]);
    dp[i][k][1] = Math.max(dp[i-1][k][1], dp[i-1][k-1][0] - prices[i]);`
这些操作中其实隐含了一些对股票的买入卖出的操作，那么就意味着循环越往后面，k的可取值范围会越来越小呀。

**Comment by DawnJF** [comment]
太感谢了，终于看懂k的含义了
