### ISSUE TITLE
bug + 学习数据结构和算法的框架思维，时间复杂度分析我认为有误

### ISSUE THREAD

**Issue by fadedzipper** [labuladong/fucking-algorithm#265]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[学习数据结构和算法的框架思维.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%AD%A6%E4%B9%A0%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%92%8C%E7%AE%97%E6%B3%95%E7%9A%84%E9%AB%98%E6%95%88%E6%96%B9%E6%B3%95.md)

问题描述：

所以说数组如果要扩容，需要重新分配一块更大的空间，再把数据全部复制过去，时间复杂度 O(N)，在这一句中我认为表述有误。

并不是说只要扩容不管扩容多少的空间，我都是一定需要O（n）的时间，因为扩容可以一次扩容一倍，那么我新分配空间的规模和我复制元素的规模，都是跟我要扩容的那个规模在常数范围内相等的，而扩容一个常数规模的均摊时间复杂度更是可以达到O(1)，所以我认为表述有误，建议修改一下

**Comment by labuladong** [comment]
感谢指出，我规范一下表述~
