### ISSUE TITLE
bug-动态规划-编辑距离

### ISSUE THREAD

**Issue by wangwangdaxian** [labuladong/fucking-algorithm#266]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/编辑距离.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E7%BC%96%E8%BE%91%E8%B7%9D%E7%A6%BB.md)

问题描述：

当s1[i]==s2[j]时，使db[i][j]=db[i-1][j-1]可能导致不正确的结果。此种情况下，仍然可以作出三种操作，只是替换字符操作的开销变成了0，但替换字符并不一定是最优操作。

正确解法应该是db[i][j]=min{db[i-1][j-1],db[i][j-1]+1,db[i-1][j]+1}

**Comment by XhqGlorry11** [comment]
@wangwangdaxian +1
