### ISSUE TITLE
bug 图片链接是不是失效了？我这边所有的图片都看不到了。

### ISSUE THREAD

**Issue by AlbertLeonard** [labuladong/fucking-algorithm#267]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/动态规划设计：最长递增子序列.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E8%AE%BE%E8%AE%A1%EF%BC%9A%E6%9C%80%E9%95%BF%E9%80%92%E5%A2%9E%E5%AD%90%E5%BA%8F%E5%88%97.md)

问题描述：

我这边显示所有图片链接失效，一直在看，之前还好好的。

**Comment by labuladong** [comment]
你网不行吧，换 5G 吧。
