### ISSUE TITLE
bug 动态规划之子序列问题解题模板

### ISSUE THREAD

**Issue by zjy45** [labuladong/fucking-algorithm#268]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/子序列问题模板.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%AD%90%E5%BA%8F%E5%88%97%E9%97%AE%E9%A2%98%E6%A8%A1%E6%9D%BF.md)

问题描述：

状态转移方程错误，导致代码错误
文章里的状态转移方程为
```
if (s[i] == s[j])
    // 它俩一定在最长回文子序列中
    dp[i][j] = dp[i + 1][j - 1] + 2;
else
    // s[i+1..j] 和 s[i..j-1] 谁的回文子序列更长？
    dp[i][j] = max(dp[i + 1][j], dp[i][j - 1]);
```
但当s=’abcda‘时，中间的’bcd‘不是回文串但因为头尾都是a，依然会加2，导致dp[0][i]会等于3
应该改为
```
if (s[i] == s[j] and dp[i + 1][j - 1] == j - i - 1)
    // 它俩一定在最长回文子序列中
    dp[i][j] = dp[i + 1][j - 1] + 2;
else
    // s[i+1..j] 和 s[i..j-1] 谁的回文子序列更长？
    dp[i][j] = max(dp[i + 1][j], dp[i][j - 1]);
```

**Comment by XingBin111** [comment]
if处要校验一下s[i: j+1]是否为回文, 你这样做无法解决"azbcdza"

**Comment by zjy45** [comment]
@XingBin111 对， 应该添加dp[i + 1][j - 1] == j - i - 1，来校验s[i: j+1]是否为回文，原文没加

**Comment by labuladong** [comment]
我没理解你们的意思，为什么要加？原文中的算法完全可以解决你们说的问题啊，运行一下结果是对的啊？

**Comment by zjy45** [comment]
```python
class Solution:
    def longestPalindrome(self, s: str) -> str:
        l = len(s)
        dp = [[0] * l for _ in range(l)]
        left, right = 0, 0
        m = 1
        for i in range(l):
            dp[i][i] = 1
        for i in range(l - 1, -1, -1):
            for j in range(i + 1, l):
                if s[i] == s[j]:
                    dp[i][j] = dp[i + 1][j - 1] + 2
                    if dp[i][j] > m:
                        m = dp[i][j]
                        left, right = i, j
                else:
                    dp[i][j] = max(dp[i][j - 1], dp[i + 1][j])
        return s[left:right+1]
```
原文中的算法的话，会报错
![image](https://user-images.githubusercontent.com/26567661/85255508-feba4080-b494-11ea-8d93-927a4683052b.png)

**Comment by labuladong** [comment]
估计是你代码翻译的错误，我的 java 代码没有都可以过测试。

**Comment by liupengfei123** [comment]
好像看到题目不一样把！  博主的例子是 [516. 最长回文子序列] （https://leetcode-cn.com/problems/longest-palindromic-subsequence/）这个， 你的例子是 最长回文子串的

**Comment by labuladong** [comment]
额，我还看了半天，楼上正解
