### ISSUE TITLE
对二分查找左边界的一个疑问 

### ISSUE THREAD

**Issue by yiliyili** [labuladong/fucking-algorithm#269]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/二分查找详解.md](https://github.com/labuladong/fucking-algorithm/blob/master/算法思维系列/二分查找详解.md)

问题描述：

二分查找中,检查左侧边界条件代码如下:
// 最后要检查 left 越界的情况
    if (left >= nums.length || nums[left] != target)
        return -1;
我觉得这里判断left == nums.length即可,因为写>=是表示left 有可能大于 nums.length,但从上边的代码和微信公众号的图来看最多是相等,不可能出现大于的情况

**Comment by SchopenhauerZhang** [comment]
同意@yiliyili的说法，但是这算优化，不算bug吧。

**Comment by labuladong** [comment]
嗯，这属于细节问题，书写习惯而已。
