### ISSUE TITLE
看这个有用么？

### ISSUE THREAD

**Issue by happysmile12321** [labuladong/fucking-algorithm#272]
我就想考过算法，看这个有用么？
有成功的大佬给出一点建议呗？

**Comment by Ethan199111** [comment]
对于小白可能用处不大，对于有经验的来说总结的非常到位，当然看多少都不如赶紧去敲几行。算法题都是越写越熟练

**Comment by labuladong** [comment]
你自己看一下不就行了么？
建议转行🤔

**Comment by happysmile12321** [comment]
> 你自己看一下不就行了么？
> 建议转行

转神马啊。我还是学生。大佬。

**Comment by happysmile12321** [comment]
> 你自己看一下不就行了么？
> 建议转行

这是大佬对我的鞭策啊。

**Comment by happysmile12321** [comment]
> 你自己看一下不就行了么？
> 建议转行

> 你自己看一下不就行了么？
> 建议转行

谢谢。也许以后能保护好头发。:joy:

**Comment by 715hang** [comment]
> 对于小白可能用处不大，对于有经验的来说总结的非常到位，当然看多少都不如赶紧去敲几行。算法题都是越写越熟练

对于编程小白用处不大，但对于算法小白来说，很有用了

**Comment by yuanliangliang** [comment]
有用没用看自己需求，合适最重要，学习具有阶段性，一般大跃进是会跌大跟头的

**Comment by GengchenXU** [comment]
对算法小白用处还是很大的

**Comment by xiechuanyu** [comment]
有用

**Comment by big-hunter** [comment]
你猜猜有啥用?
