### ISSUE TITLE
bug-KMP字符匹配算法中有讲解错误 

### ISSUE THREAD

**Issue by heyblackC** [labuladong/fucking-algorithm#274]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/KMP字符匹配算法](https://labuladong.gitbook.io/algo/dong-tai-gui-hua-xi-lie/dong-tai-gui-hua-zhi-kmp-zi-fu-pi-pei-suan-fa)

问题描述：
您在第三部分构建状态转移图中，对影子状态有如下描述：

> 所谓影子状态，就是和当前状态具有相同的前缀。

并举例了下图为证：
![image](https://user-images.githubusercontent.com/44136207/80607545-380f9a80-8a68-11ea-94ad-bf2d9136a052.png)

但我们看过KMP原始算法就会知道，影子状态应该定义为：找到当前状态的最长相同前缀和后缀。图中的例子里，j指向4，x指2，是因为前缀AB和后缀AB相同，所以j才能代理给x处理。

**仅仅一句和当前状态有相同的前缀，这是错误的。**

我相信不必多言前后缀，您也能明白我的意思，如有讲错的，还请相互探讨探讨。

=====================================

下面对前后缀进一步解释：
"部分匹配值"就是"前缀"和"后缀"的最长的共有元素的长度。以"ABCDABD"为例，
```　　－　"A"的前缀和后缀都为空集，共有元素的长度为0；

　　－　"AB"的前缀为[A]，后缀为[B]，共有元素的长度为0；

　　－　"ABC"的前缀为[A, AB]，后缀为[BC, C]，共有元素的长度0；

　　－　"ABCD"的前缀为[A, AB, ABC]，后缀为[BCD, CD, D]，共有元素的长度为0；

　　－　"ABCDA"的前缀为[A, AB, ABC, ABCD]，后缀为[BCDA, CDA, DA, A]，共有元素为"A"，长度为1；

　　－　"ABCDAB"的前缀为[A, AB, ABC, ABCD, ABCDA]，后缀为[BCDAB, CDAB, DAB, AB, B]，共有元素为"AB"，长度为2；

　　－　"ABCDABD"的前缀为[A, AB, ABC, ABCD, ABCDA, ABCDAB]，后缀为[BCDABD, CDABD, DABD, ABD, BD, D]，共有元素的长度为0。
```

**Comment by labuladong** [comment]
这是参考《算法4》的 KMP 算法，实际上不是原始的 KMP 算法，而是 DFA 状态机，和后缀似乎没什么关系
