### ISSUE TITLE
bug “where command not found”

### ISSUE THREAD

**Issue by wangzy0327** [labuladong/fucking-algorithm#275]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[技术/linux.md](https://github.com/labuladong/fucking-algorithm/blob/master/技术/linuxshell.md)

问题描述：

某章图片链接失效/其中的 XXX 内容有误/等等。

**Comment by ViggoC** [comment]
`where` 应该不是 `bash` 的内建命令，`zsh` 和 `cmd` 中倒是都有 `where` 命令。

**Comment by ViggoC** [comment]
此外这篇文章中的`nohub`也是错误的写法，应该是`nohup`。

**Comment by labuladong** [comment]
笔误已修复，另外，这种问题直接百度，别在这题 issue。
