### ISSUE TITLE
关于文中的语言问题

### ISSUE THREAD

**Issue by GGGWB** [labuladong/fucking-algorithm#280]
现在文中经常java，python，c++混杂，强烈建议用几种语言共同编辑一下，比如我只会python，Java略懂，看C++的时候很吃力，时不时停顿查阅相关语法严重影响了学习的时候的思维，小菜鸡不敢提pr，希望您能有空维护一下，相信会帮助更多的算法初学者！祝Number of stars up up up！

**Comment by lemonade117** [comment]
我也是，只会python和C++, 看java的时候好吃力

**Comment by labuladong** [comment]
严重影响了思维？这个问题应该由谁解决呢？

**Comment by GGGWB** [comment]
> 严重影响了思维？这个问题应该由谁解决呢？

我是提个建议，既然已经写成了系列何不和《漫画算法》这本书作者一样写不同语言呢，我自己自学了Java基础看您文章和公众号也没有问题，只是作为粉丝提建议而已……没有别的意思

**Comment by labuladong** [comment]
收到建议，可以参与 pr 提交其他语言的解法代码

guowenbiao <notifications@github.com> 于2020年6月19日周五 下午11:43写道：
