### ISSUE TITLE
大哥。这本小册子的书籍啥时候可以出来?

### ISSUE THREAD

**Issue by jiayoujyjyjy** [labuladong/fucking-algorithm#281]

**Comment by labuladong** [comment]
稍安勿躁，面包会有的，牛奶会有的🤣

**Comment by goodgoodwish** [comment]
您的系列文章, 精准扼要, 简洁而全面.  您说不更新 GitHub 了. 以后去哪里看您的新文章呢?

**Comment by labuladong** [comment]
公众号一直在更新

Charlie Yi Zhu 木匠 <notifications@github.com> 于2020年8月17日周一 上午1:10写道：

**Comment by lancelot96** [comment]
同求电子书格式

**Comment by labuladong** [comment]
公众号后台回复「pdf」可以免费下载电子书

yuyy <notifications@github.com> 于2020年8月31日周一 下午5:23写道：

**Comment by lancelot96** [comment]
希望提供其他电子书格式，比如 mobi, epub 等。因为 pdf 在 kindle 上效果不是很好，而且这个 pdf 已经两次使我的 kindle 卡在白屏了。

**Comment by lancelot96** [comment]
> 因为pdf在kindle上效果不是很好，而且这个pdf已经两次使我的kindle卡在白屏了。

期望提供其他格式的电子书，比如 mobi 或者 epub。

**Comment by fierceX** [comment]
电子书格式可以自己动手，作者已经把主要的文章都放到github上了，你们还不能转成epub，mobi格式的吗。查查gitbook，十分钟就能搞定。
