### ISSUE TITLE
bug-双指针技巧确定单链表环起点的一个描述问题

### ISSUE THREAD

**Issue by AlieZ22** [labuladong/fucking-algorithm#283]
大佬好，我发现如下文章可能描述有点问题（点击文字可跳转到相关文章）：

[算法思维系列/双指针技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%8F%8C%E6%8C%87%E9%92%88%E6%8A%80%E5%B7%A7.md)

问题描述：

原文说的是“第一次相遇时，假设慢指针 slow 走了 k 步，那么快指针 fast 一定走了 2k 步，也就是说比 slow 多走了 k 步（也就是环的长度）。”，我觉得括号内应该是环的长度或环长度的倍数。
假设一个有环的单链表，head距环起点的距离为10m，环长度3m。A(slow)速度1m/s，B(fast)速度2m/s。那么在12s时两者相遇。

**Comment by tfzxyinhao** [comment]
+1

**Comment by XuKai1991** [comment]
这种证明方法确实是有问题的，包括网上很多证明都是这么描述的，尽管结论是正确的，但证明过程不对

**Comment by labuladong** [comment]
👍，已修复
