### ISSUE TITLE
bug 动态规划之博弈问题

### ISSUE THREAD

**Issue by superDoubling** [labuladong/fucking-algorithm#286]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划之博弈问题.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E4%B9%8B%E5%8D%9A%E5%BC%88%E9%97%AE%E9%A2%98.md)

问题描述：

文中说石头游戏二维数组只能斜着遍历、这边可以倒着遍历，会比较好理解。
`for (int i = n - 1; i >= 0; i--) {
            for (int j = i + 1; j < n; j++) {
                ...
            }
        }`

**Comment by labuladong** [comment]
可以的，后面的文章有提到倒着遍历的方法
