### ISSUE TITLE
动态规划：House Robber I篇 怀疑未注明参考原文出处

### ISSUE THREAD

**Issue by Huixxi** [labuladong/fucking-algorithm#292]
请问您的“动态规划：House Robber I篇`是否有参考该问题LeetCode上的第一个高赞讲解，如果是的话还请麻烦注明源参考链接。https://leetcode.com/problems/house-robber/discuss/156523/From-good-to-great.-How-to-approach-most-of-DP-problems.

**Comment by Huixxi** [comment]
请问您的“动态规划：博弈问题篇`是否有参考该问题油管大神Tushar Roy的讲解，如果是的话还请麻烦注明源参考链接。Optimal Strategy Game Pick from Ends of array Dynamic Programming：https://www.youtube.com/watch?v=WxpIHvsu1RI

**Comment by xueyuanl** [comment]
请问关于以上两个问题是否属实? 还请麻烦回答一下。

**Comment by Huixxi** [comment]
请问您的“动态规划：高楼扔鸡蛋篇`是否有参考该问题LeetCode原题的官方Solution，如果是的话还请麻烦注明源参考链接。https://leetcode.com/problems/super-egg-drop/solution/

**Comment by Huixxi** [comment]
说明一下，我不是来专门挑作者的刺的，我觉得作者写的浅显易懂，沁人心脾，只不过我在学习的过程中发现了一些与网上已有解答十分雷同的地方，觉得作者在尊重事实的前提下有必要注明一下参考的出处，作者有些地方也做了参考标注，我觉得尊重别人的成果才是对自己成果的最大尊重，这些地方可能就是作者自己的想法我作为一个外人想多了，也可能是事实如此只是作者忘了标，毕竟这么多star的repo，这么多优质文章维护起来有点麻烦。不过我想还是应该严谨一点，不是简单翻译再融入点自己的想法就变成了自己的东西，毕竟拿来主义是令人十分厌恶的，我的初衷也是希望这个repo能变得更好，有些杠精和傻逼想过来插一嘴的还是省省，我特么哪里动了你的奶酪了。

**Comment by xueyuanl** [comment]
> 说明一下，我不是来专门挑作者的刺的，我觉得作者写的浅显易懂，沁人心脾，只不过我在学习的过程中发现了一些与网上已有解答十分雷同的地方，觉得作者在尊重事实的前提下有必要注明一下参考的出处，作者有些地方也做了参考标注，我觉得尊重别人的成果才是对自己成果的最大尊重，这些地方可能就是作者自己的想法我作为一个外人想多了，也可能是事实如此只是作者忘了标，毕竟这么多star的repo，这么多优质文章维护起来有点麻烦。不过我想还是应该严谨一点，不是简单翻译再融入点自己的想法就变成了自己的东西，毕竟拿来主义是令人十分厌恶的，我的初衷也是希望这个repo能变得更好，有些杠精和傻逼想过来插一嘴的还是省省，我特么哪里动了你的奶酪了。

我提问不严谨，产生了误解，我已经修改提问了。也请你把脏字修改掉，谢谢。

**Comment by xueyuanl** [comment]
而且我觉得，这不是拿来主义这么简单。如果后边准备出版，就是商业行为，不加引用的话就是侵权和抄袭，这个是我个人完全不能接受的。

**Comment by labuladong** [comment]
我肯定是参考过别人的文章，有些确实没有标注，我的锅，抽空加上。不过，有的问题，你们确实想的有点多了🤔
