### ISSUE TITLE
动态规划篇的疑问

### ISSUE THREAD

**Issue by Jesse-so-cool** [labuladong/fucking-algorithm#294]
问题描述：
涉及文章：[最大递增子序列文章](https://labuladong.gitbook.io/algo/dong-tai-gui-hua-xi-lie/dong-tai-gui-hua-she-ji-zui-chang-di-zeng-zi-xu-lie)

作者你好，我记得在之前的的套路框架篇说后续的文章都会以套路的思想辅助理解，但在最大递增子序列文章中，发现并没有提及相应的“状态”，“选择”，“最优子”。
请问是我理解错了吗，因为我本想套路式的去学习动态规划，却发现又回到了乱摸索的起初的学习样子

**Comment by labuladong** [comment]
把所有动态规划系列的文章看完，你就有感觉了。
