### ISSUE TITLE
bug 回溯算法详解中，多叉树的遍历框架

### ISSUE THREAD

**Issue by Tsingsin** [labuladong/fucking-algorithm#295]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/回溯算法详解修订版.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%9B%9E%E6%BA%AF%E7%AE%97%E6%B3%95%E8%AF%A6%E8%A7%A3%E4%BF%AE%E8%AE%A2%E7%89%88.md)

问题描述：

多叉树的遍历框架内容有误。
```
void traverse(TreeNode root) {
    for (TreeNode child : root.childern)
        // 前序遍历需要的操作
        traverse(child);
        // 后序遍历需要的操作
}
```
应为
```
void traverse(TreeNode root) {
    // 前序遍历需要的操作
    for (TreeNode child : root.childern){
          traverse(child);
    }
    // 后序遍历需要的操作
}
```

**Comment by labuladong** [comment]
emmm，有道理，区别就是前者不会遍历 root 节点。不过回溯树的根节点是虚拟的，所以不需要太计较这个细节。

**Comment by YumeMichi** [comment]
竟然是同款头像233

**Comment by Tsingsin** [comment]
> 竟然是同款头像233

**Comment by Tsingsin** [comment]
> 竟然是同款头像233

哈哈

**Comment by labuladong** [comment]
两个社会人，相遇是缘分，reopen issue 干嘛

**Comment by ihewro** [comment]
可以说明一下，刚才看到这里迷茫住了～～～
