### ISSUE TITLE
经典动态规划：完全背包问题

### ISSUE THREAD

**Issue by Jesse-so-cool** [labuladong/fucking-algorithm#298]
你好，我发现如下文章有问题（点击文字可跳转到相关文章）：

[经典动态规划：完全背包问题.md](https://labuladong.gitbook.io/algo/dong-tai-gui-hua-xi-lie/bei-bao-ling-qian)

问题描述：
文章中，有这么一句话
![image](https://user-images.githubusercontent.com/31425351/84968046-27b29c80-b148-11ea-8c54-8aecb4c23c32.png)
疑问：
这里的j-coins[i-1]不应该是j-coins[i-1]*k吗？(k等于任意整数)
意思就是，不应该是可以拿任意枚i硬币都是要求的吗？

我的解法：
`
for (int i = 1; i <= coins.length; i++) {

            for (int j = 1; j <= amount; j++) {

                int chooseI = 0;
                for (int k = 1; k < Integer.MAX_VALUE; k++) {

                    if (j-coins[i-1]*k >=0) {
                        chooseI += dp[i-1][j-coins[i-1]*k];//选择i 说明
                    }else {
                        break;
                    }

                }
                int dontChooseI = dp[i-1][j];//选择i 说明
                dp[i][j] = dontChooseI + chooseI;
            }
        }
`

但是我用作者的代码，好像也能跑，这是我最不解的地方，求解惑

**Comment by GreenGums** [comment]
兄弟，我和你有一模一样的问题，你这里想明白了吗。麻烦解答一下

**Comment by Jesse-so-cool** [comment]
> 兄弟，我和你有一模一样的问题，你这里想明白了吗。麻烦解答一下

没明白，东哥也不回我 哭了

**Comment by GreenGums** [comment]
我看到你把issue关闭了我以为你知道了。你把这个issue打开吧。说不定有大佬看到了能够解答一下。

**Comment by c-xyz** [comment]
这道题是完全背包，j++ (amount)就暗示了乘以k的情况。拿01背包来对比就会发现，01背包必须要 j-- (j是amount)。
（所以楼主的解法有j++ 又*k，其实是多余的，但并不会导致错误。）

**Comment by KevinZhoutianyi** [comment]
class Solution {
public:
    int change(int amount, vector<int>& coins) {

        vector<vector<int>> dp(coins.size()+1,vector<int>(amount+1,0));

        dp[0][0] = 1;

        for(int i = 1 ; i <= coins.size(); i ++){
            for(int j = 0; j <= amount; j++){
                int temp = j;
                while(temp>=0){
                    dp[i][j]+=dp[i-1][temp];
                    temp = temp - coins[i-1];
                }
            }
        }
        return dp[coins.size()][amount];

    }
};

不应该这样吗。。
求解答

**Comment by simpzan** [comment]
这里有一个细节作者没有讲清楚。对比前面的子集背包问题的区别，`dp[i][j] = dp[i - 1][j] + dp[i][j - coins[i-1]]`，这里+后面的dp的第一个索引是`i`，而不是`i-1`，表示使用前i个货币凑齐`j-coins[i-1]`，所以就不需要考虑`当前货币*N`的情况了。
另外正因为这一点，在进行空间压缩的时候，没有采用子集背包问题的倒序遍历，因为根据依赖关系，只能采用正序编译。

这个问题希望作者更新一下文章，说明一下这一点。  @labuladong 

```
int change(int amount, int[] coins) {
    int n = coins.length;
    int[][] dp = amount int[n + 1][amount + 1];
    // base case
    for (int i = 0; i <= n; i++) 
        dp[i][0] = 1;

    for (int i = 1; i <= n; i++) {
        for (int j = 1; j <= amount; j++)
            if (j - coins[i-1] >= 0)
                dp[i][j] = dp[i - 1][j] 
                         + dp[i][j - coins[i-1]]; // attention here
            else 
                dp[i][j] = dp[i - 1][j];
    }
    return dp[n][amount];
}
```

**Comment by Jesse-so-cool** [comment]
> 我看到你把issue关闭了我以为你知道了。你把这个issue打开吧。说不定有大佬看到了能够解答一下。

我似乎没关过吧

**Comment by zsjun** [comment]
这里的j-coins[i-1]不应该是j-coins[i-1]*k吗？(k等于任意整数)
意思就是，不应该是可以拿任意枚i硬币都是要求的吗？

你这里的理解是错误的。
dp[j-coins[i-1]]这里是把你说的这几种情况给包括了的，比如这里
<img width="566" alt="图片" src="https://user-images.githubusercontent.com/8063904/102177722-107a1f00-3edf-11eb-8c1e-9e9183dc0238.png">

在完全背包问题中，一个物品可以拿多次。如图上半部分所示，假设我们遍历到物品 i = 2， 且其体积为 w = 2，价值为 v = 3;对于背包容量 j = 5，最多只能装下 2 个该物品。那么我们的状 态转移方程就变成了 dp[2][5] = max(dp[1][5], dp[1][3] + 3, dp[1][1] + 6)。如果采用这种方法，假设 背包容量无穷大而物体的体积无穷小，我们这里的比较次数也会趋近于无穷大，远超 O(NW) 的 时间复杂度。
怎么解决这个问题呢?我们发现在 dp[2][3] 的时候我们其实已经考虑了 dp[1][3] 和 dp[2][1] 的情况，而在时 dp[2][1] 也已经考虑了 dp[1][1] 的情况。因此，如图下半部分所示，对于拿多个 物品的情况，我们只需考虑 dp[2][3] 即可，即 dp[2][5] = max(dp[1][5], dp[2][3] + 3)。这样，我们 就得到了完全背包问题的状态转移方程:dp[i][j] = max(dp[i-1][j], dp[i][j-w] + v)，其与 0-1 背包问 题的差别仅仅是把状态转移方程中的第二个 i-1 变成了 i。

可以看到dp[2][5] = max(dp[1][5], dp[1][3] + 3, dp[1][1] + 6) = max(dp[1][5], (dp[1][3], dp[1][1] + 3) +3) = 
max(dp[1][5], dp[2][3] +3)
