### ISSUE TITLE
第零章的BMF框架中的二叉树的最小深度leetCode链接错误

### ISSUE THREAD

**Issue by GreenGums** [labuladong/fucking-algorithm#299]
链接地址 
[https://labuladong.gitbook.io/algo/di-ling-zhang-bi-du-xi-lie/bfs-kuang-jia](url)
https://labuladong.gitbook.io/algo/di-ling-zhang-bi-du-xi-lie/bfs-kuang-jia

**Comment by labuladong** [comment]
收到，已修改，谢谢指出
