### ISSUE TITLE
二叉树框架思维404了

### ISSUE THREAD

**Issue by Rye-T** [labuladong/fucking-algorithm#3]
二叉树的框架思维404了

**Comment by labuladong** [comment]
哪个？我咋没看到有 404 的，发链接出来看看？

**Comment by labuladong** [comment]
好吧，我找到了，已修复

**Comment by Rye-T** [comment]
https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%AD%A6%E4%B9%A0%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%92%8C%E7%AE%97%E6%B3%95%E7%9A%84%E6%A1%86%E6%9E%B6%E6%80%9D%E7%BB%B4.md

**Comment by Rye-T** [comment]
https://github.com/labuladong/fucking-algorithm/blob/master/算法思维系列/学习数据结构和算法的框架思维.md

**Comment by labuladong** [comment]
明白了，链接错了，已经在最近的 commit 中修复了
