### ISSUE TITLE
需要多语言版本的题解，master 开始接受 pr

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#301]
## 由于所有文章的结构更新，重新开放 pr

**一、需求**：

labuladong 的题解是混用 C++，Java，Python3 几种语言的，有的读者表示并不是每一种语言都熟悉，所以现在希望每个题解都有以上三种语言的版本（暂不接受其他语言版本）。

**二、对你的好处**：

**成为本仓库的 direct contributor，和 labuladong 肩并肩**。这么火的一个仓库，你是 direct contributor，保准把别人吓个跟头。

![](https://raw.githubusercontent.com/labuladong/fucking-algorithm/master/contributor.jpg)

**三、pr 的要求也比较苛刻**：

1、代码运行速度至少击败 95% 的对手，需要在 pr 时放截图为据（考虑到 LeetCode 的时间计算不一定准确，这个可以根据具体题目酌情）。

2、代码可读性为首要指标，注释完整，其他语言版本的注释详细程度不能小于 labuladong 版本代码的注释。不能出现任何语言层面的技巧，绝对拒绝秀操作。

3、pr 格式要统一，下面会给出一个模板，按照这个格式增加新语言的解法代码。

**Comment by labuladong** [comment]
1、多语言的解法代码在写在原始文章的什么位置？

**写在二维码下方，页脚上方，参考这篇文章的示例：[合法括号判定](https://github.com/labuladong/fucking-algorithm/blob/master/%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97/%E5%90%88%E6%B3%95%E6%8B%AC%E5%8F%B7%E5%88%A4%E5%AE%9A.md)**。注意要把 labuladong 原来的解法代码也 copy 过去，然后新增其他语言的解法代码。

2、个人链接可以链接到哪里？

[张三](any_link_you_want) 提供 Java 代码：
```java
public void func() {
    //......
}
```

你可以链接到任何你希望的地方，比如说你的 GitHub profile 页面，或者你的个人博客。

3、一篇文章有多个题解怎么办？

把多个题解都写出来。

4、提交 pr 时，需要提供 LeetCode/力扣 的运行结果：

![image](https://user-images.githubusercontent.com/37220920/85233050-3f36a180-b436-11ea-9dc2-defff97beff7.png)

**Comment by CNXYQ** [comment]
提交判断回文链表的Python解法 #349

**Comment by CNXYQ** [comment]
提交判断回文链表的Python解法 #349

**Comment by CNXYQ** [comment]
**提交判断回文链表的Python解法** #349

**Comment by CNXYQ** [comment]
> [提交判断回文链表的Python解法#349](https://github.com/labuladong/fucking-algorithm/pull/349)

**Comment by CNXYQ** [comment]
> 1、**多语言的解法代码在写在原始文章的什么位置**？
> 
> **写在文末二维码下方，页脚上方，参考这篇文章的示例：[合法括号判定](https://github.com/labuladong/fucking-algorithm/blob/master/%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97/%E5%90%88%E6%B3%95%E6%8B%AC%E5%8F%B7%E5%88%A4%E5%AE%9A.md)**。
> 
> 2、**个人链接可以链接到哪里**？
> 
> [张三](any_link_you_want) 提供 Java 代码：
> 
> ```java
> public void func() {
>     //......
> }
> ```
> 
> 你可以链接到任何你希望的地方，比如说你的 GitHub profile 页面，或者你的个人博客。
> 
> 3、**一篇文章有多个题解怎么办**？
> 
> 把多个题解都写出来。
> 
> 4、**提交 pr 时，需要提供 LeetCode/力扣 的运行结果**：
> 
> ![image](https://user-images.githubusercontent.com/37220920/85233050-3f36a180-b436-11ea-9dc2-defff97beff7.png)

**提交判断回文链表的Python解法#349**

**Comment by kingkong1111** [comment]
![image](https://user-images.githubusercontent.com/49048732/85385044-698e7900-b574-11ea-9e17-8d6fc6005cdd.png)

**Comment by zjsywc** [comment]
henbang
