### ISSUE TITLE
bug - English gitbook typo

### ISSUE THREAD

**Issue by lizlu95** [labuladong/fucking-algorithm#340]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[Dynamic Programming in Detials](https://labuladong.gitbook.io/algo-en/i.-dynamic-programming/analysisofdynamicprogramming)

问题描述：

在英文版本的gitbook中，链接里文章的标题有typo。应为Dynamic Programming in Details.

**Comment by labuladong** [comment]
好的
