### ISSUE TITLE
`translate 动态规划系列/编辑距离.md`

### ISSUE THREAD

**Issue by bailixuance** [labuladong/fucking-algorithm#36]
我将开始翻译如下文章（点击可查看目标文章）：

[动态规划系列/编辑距离.md](https://github.com/labuladong/fucking-algorithm/blob/master/动态规划系列/编辑距离.md)

我准备将它翻译成：**英文**

**预计 10 天内翻译完成**，若由于种种原因没有完成，如果你愿意，你可以接替我的工作翻译这篇文章。

**Comment by labuladong** [comment]
感谢参与，该文章的翻译已完成
