### ISSUE TITLE
二分查找子序列的那个

### ISSUE THREAD

**Issue by BigPayno** [labuladong/fucking-algorithm#386]
其实就是来夸下这个仓库，太牛了，看你的教程我觉得我能两周刷完，讲得都很透彻本质

二分查找子序列问题其实就是重复子问题太多

然后为了迅速排除无效条件，使用了削弱条件，先找必要条件(筛)，然后证明充分性(高中数学的感觉)

然后利用备忘录记录重复子问题

你的仓库写得太棒了，看你的教程就像是未来的自己来教自己(太高效了)，如果自己搞还得刷好久

**Comment by yuanliangliang** [comment]
同感，论思路的重要性！简单明了，一针见血！
