### ISSUE TITLE
你的這些東西Wiki都有, 要你何用

### ISSUE THREAD

**Issue by Imputes** [labuladong/fucking-algorithm#387]
不要誤人子弟, 搞這種東西出來博流量

**Comment by yuanliangliang** [comment]
这貌似不算是个问题，作为资深潜水人士冒个泡，交流一下。首先，并不是每个人都上wiki,正如不是每个人都是十项全能一样，每个人都有自己的活法和获取信息的方式。就像北方人爱吃面，南方人爱吃饭一样，合适自己才最重要，至于好不好，其实在有限的时空里，没有绝对的好与坏。

**Comment by xiechuanyu** [comment]
有用
