### ISSUE TITLE
如何用 BFS 算法秒杀各种智力题建议

### ISSUE THREAD

**Issue by Light-City** [labuladong/fucking-algorithm#397]
作者给出的思路中：neighbor 数组需要提前计算，这里给出一个不需要该数组的方法。

实际上是二维转一维的方法。
对于二维数组中board[i][j]->arr[i*m+j]，m为列长度，那么这道题直接根据一维Index->二维位置与二维index->一维index，可以非常方便找到上下左右点，具体AC代码如下：

```cpp
class Solution {
private:
    int d[4][2] = {
        {1,0},
        {-1,0},
        {0,1},
        {0,-1}
    };
    int n,m;
public:
    int slidingPuzzle(vector<vector<int>>& board) {
        n = board.size();
        m = board[0].size();
        string start = boardToString(board);
        int step = 0;
        unordered_set<string> s;
        queue<string> q;
        q.push(start);
        s.insert(start);
        while(!q.empty()) {
            int sz = q.size();
            for (int i=0;i<sz;i++) {
                string cur = q.front();
                q.pop();
                if (cur == "123450") return step;
                int index = cur.find('0');
                int x=index/m;
                int y=index%m;
                for (int j=0;j<4;j++) {
                    int x1 = x+d[j][0];
                    int y1 = y+d[j][1];
                    if(inBoard(x1,y1)) {
                        string tmp = cur;
                        swap(tmp[index],tmp[x1*m+y1]);
                        if(!s.count(tmp)) {
                            q.push(tmp);
                            s.insert(tmp);
                        }
                    }
                }
            }
            step++;
        }

        return -1;
    }   
    bool inBoard(int x,int y) {
        return x>=0&&x<n&&y>=0&&y<m;
    }
    string boardToString(const vector<vector<int>>& board) {
        string res="";
        for (auto elem : board) 
            for (auto e : elem) res+=to_string(e);
        return res;
    }   
};
```

**Comment by Light-City** [comment]
> 作者给出的思路中：neighbor 数组需要提前计算，这里给出一个不需要该数组的方法。
> 
> 实际上是二维转一维的方法。
> 对于二维数组中board[i][j]->arr[i*m+j]，m为列长度，那么这道题直接根据一维Index->二维位置与二维index->一维index，可以非常方便找到上下左右点，具体AC代码如下：
> 
> ```c++
> class Solution {
> private:
>     int d[4][2] = {
>         {1,0},
>         {-1,0},
>         {0,1},
>         {0,-1}
>     };
>     int n,m;
> public:
>     int slidingPuzzle(vector<vector<int>>& board) {
>         n = board.size();
>         m = board[0].size();
>         string start = boardToString(board);
>         int step = 0;
>         unordered_set<string> s;
>         queue<string> q;
>         q.push(start);
>         s.insert(start);
>         while(!q.empty()) {
>             int sz = q.size();
>             for (int i=0;i<sz;i++) {
>                 string cur = q.front();
>                 q.pop();
>                 if (cur == "123450") return step;
>                 int index = cur.find('0');
>                 int x=index/m;
>                 int y=index%m;
>                 for (int j=0;j<4;j++) {
>                     int x1 = x+d[j][0];
>                     int y1 = y+d[j][1];
>                     if(inBoard(x1,y1)) {
>                         string tmp = cur;
>                         swap(tmp[index],tmp[x1*m+y1]);
>                         if(!s.count(tmp)) {
>                             q.push(tmp);
>                             s.insert(tmp);
>                         }
>                     }
>                 }
>             }
>             step++;
>         }
> 
>         return -1;
>     }   
>     bool inBoard(int x,int y) {
>         return x>=0&&x<n&&y>=0&&y<m;
>     }
>     string boardToString(const vector<vector<int>>& board) {
>         string res="";
>         for (auto elem : board) 
>             for (auto e : elem) res+=to_string(e);
>         return res;
>     }   
> };
> ```

补充一下对应的dfs。

```cpp
class Solution {
private:
    int d[4][2] = {
        {1,0},
        {-1,0},
        {0,1},
        {0,-1}
    };
    int n,m;
    // unordered_set<string> visited;
    unordered_map<string,int> um;
    int ret;
public:
    int slidingPuzzle(vector<vector<int>>& board) {
        n = board.size();
        m = board[0].size();
        ret = INT_MAX;
        string start = boardToString(board);
        // visited = unordered_set<string>();
        um = unordered_map<string,int>();
        dfs(start,0);
        return ret == INT_MAX ? -1 : ret;
    }   

    void dfs(string s,int ans) {
        if (s == "123450") ret = min(ret, ans);
        if (ans > ret || (um[s] != 0 && um[s] <= ans)) return ;
        int index = s.find('0');
        int x=index/m;
        int y=index%m;

        um[s] = ans;    // visited 更新
        for (int j=0;j<4;j++) {
            int x1 = x+d[j][0];
            int y1 = y+d[j][1];
            if(inBoard(x1,y1)) {
                swap(s[index],s[x1*m+y1]);
                dfs(s,ans+1);
                swap(s[x1*m+y1],s[index]);
            }
        }   
        return;
    }
    bool inBoard(int x,int y) {
        return x>=0&&x<n&&y>=0&&y<m;
    }
    string boardToString(const vector<vector<int>>& board) {
        string res="";
        for (auto elem : board) 
            for (auto e : elem) res+=to_string(e);
        return res;
    }   
};
```

**Comment by labuladong** [comment]
嗯，有道理，核心是这几行对吧

![image](https://user-images.githubusercontent.com/37220920/87228698-82e94f00-c3d5-11ea-9487-38137d9b4c66.png)
