### ISSUE TITLE
Stock problems 第六题 Python code bug

### ISSUE THREAD

**Issue by davidweinfls** [labuladong/fucking-algorithm#401]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[团灭股票问题](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%9B%A2%E7%81%AD%E8%82%A1%E7%A5%A8%E9%97%AE%E9%A2%98.md)

问题描述：

第六题 k = any integer
Template中没有明确指出当k=1，dp[i-1][k-1][0]可能出现错误 导致Python的code是错误的

```
def maxProfit_k_any(self, max_k: int, prices: List[int]) -> int:
    n = len(prices)
    if max_k > n // 2:
        return self.maxProfit_k_inf(prices)
    else:
        dp = [[[None, None] for _ in range(max_k + 1)] for _ in range(n)]
        for i in range(0,n):
            for k in range(max_k,0,-1):
                if i-1 == -1:## 处理 base case
                    dp[i][k][0] = 0
                    ## 解释：
                    ## dp[i][k][0] = max(dp[-1][k][0], dp[-1][k][1] + prices[i])
                    ## = max(0, -infinity + prices[i]) = 0
                    dp[i][k][1] = -prices[i]
                    ## 解释：
                    ## dp[i][1] = max(dp[-1][k][1], dp[-1][k][0] - prices[i])
                    ## = max(-infinity, 0 - prices[i]) = -prices[i]
                    continue
                dp[i][k][0] = max(dp[i-1][k][0], dp[i-1][k][1] + prices[i])
                dp[i][k][1] = max(dp[i-1][k][1], dp[i-1][k-1][0] - prices[i]) # <= k-1 is not initialized
        return dp[n - 1][max_k][0];
```
![Screen Shot 2020-06-27 at 18 59 55](https://user-images.githubusercontent.com/4341317/85935687-81ce0300-b8a8-11ea-8805-5cb9318d3448.png)

solution应该初始化k=0的情况 （类似于CPP的solution）或者在for loop中handle `if k == 0`.  同时建议解释一下为什么从 倒过来从range(max_k, 0, -1) loop k， 感觉正过来从`for k in range(max_k + 1)`也完全可行

如果make sense 我可以发PR来修复

**Comment by PredawnRaziel** [comment]
我认为 k 不是可以正着来，而是应该正着来
毕竟是 dp[k] = dp[k-1] 类的情况，应该保证顺序初始化

**Comment by labuladong** [comment]
直接提 pr
