### ISSUE TITLE
题解代码建议

### ISSUE THREAD

**Issue by KODGV** [labuladong/fucking-algorithm#406]
我感觉现在这样把题解代码写到文章里面不是很好，应该单独做个链接在结尾。不然有的文章3个题，对应3个版本，9个题解代码我觉得太多了。

**Comment by labuladong** [comment]
不就是放在结尾的么？

KODGV <notifications@github.com> 于2020年6月30日周二 上午10:05写道：

**Comment by KODGV** [comment]
我的意思是题解做成单独一个文件，然后把链接放在结尾
