### ISSUE TITLE
how to export gitbook into pdf format?

### ISSUE THREAD

**Issue by jamesanse** [labuladong/fucking-algorithm#411]
请问https://labuladong.gitbook.io/algo-en/v/master/ 里的内容可以导出pdf 文档么
感谢🙏

**Comment by labuladong** [comment]
公众号后台回复关键词 pdf 可以下载

James An <notifications@github.com> 于2020年7月3日周五 上午8:59写道：

**Comment by consideration-ak** [comment]
为什么传到百度网盘? 可否在谷歌云盘上传一份, 百度网盘龟速根本无法下载

**Comment by labuladong** [comment]
@consideration-ak 过了七天了，应该下好了吧

**Comment by consideration-ak** [comment]
@labuladong 对的, 群友压缩后传了一份
