### ISSUE TITLE
bug: 动态规划解题套路框架的 dp数组的迭代解法

### ISSUE THREAD

**Issue by parzulpan** [labuladong/fucking-algorithm#421]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划解题套路框架/dp数组的迭代解法](https://labuladong.gitbook.io/algo/dong-tai-gui-hua-xi-lie/dong-tai-gui-hua-xiang-jie-jin-jie#yi-fei-bo-na-qi-shu-lie)

问题描述：
没考虑边界条件，运行出错。

## 原代码
```
int fib(int N) {
    vector<int> dp(N + 1, 0);
    // base case
    dp[1] = dp[2] = 1;
    for (int i = 3; i <= N; i++)
        dp[i] = dp[i - 1] + dp[i - 2];
    return dp[N];
}
```
**没有考虑N为0、1的情况。**

**Comment by MoguCloud** [comment]
N 为 0 的情况 
在第2行 `vector<int> dp(N + 1, 0);`  
第2个参数是初始值，所以 dp[0]  为 0

N 为 1 的情况 
在第4行 `dp[1] = dp[2] = 1;`   
dp[1] 为 1

**Comment by parzulpan** [comment]
> N 为 0 的情况
> 在第2行 `vector<int> dp(N + 1, 0);`
> 第2个参数是初始值，所以 dp[0] 为 0
> 
> N 为 1 的情况
> 在第4行 `dp[1] = dp[2] = 1;`
> dp[1] 为 1

N 为 0 的情况时，给向量分配了1个int，使用dp[2]会报错，因为没有dp[2没分配空间。

**Comment by parzulpan** [comment]
> N 为 0 的情况
> 在第2行 `vector<int> dp(N + 1, 0);`
> 第2个参数是初始值，所以 dp[0] 为 0
> 
> N 为 1 的情况
> 在第4行 `dp[1] = dp[2] = 1;`
> dp[1] 为 1

N 为 0 的情况，dp[2]都没有给空间的，肯定出错的。

**Comment by parzulpan** [comment]
> N 为 0 的情况
> 在第2行 `vector<int> dp(N + 1, 0);`
> 第2个参数是初始值，所以 dp[0] 为 0
> 
> N 为 1 的情况
> 在第4行 `dp[1] = dp[2] = 1;`
> dp[1] 为 1

N 为 0 的情况，dp[2]没有分配空间，显然是由歧义的。可以看到，不同编译器可能有不同处理。

以下为LeetCode，报错。
![image](https://user-images.githubusercontent.com/34685042/87779211-059f5d80-c85f-11ea-9794-9c9c3524cc75.png)

以下为本地MinGW，正常。
![image](https://user-images.githubusercontent.com/34685042/87779390-49926280-c85f-11ea-8750-dc3193955a64.png)

**Comment by labuladong** [comment]
把 0 的情况排一下即可：

```cpp
int fib(int N) {
    if (N == 0) return 0;
    if (N == 1 || N == 2) return 1;
    vector<int> dp(N + 1, 0);
    // base case
    dp[1] = dp[2] = 1;
    for (int i = 3; i <= N; i++)
        dp[i] = dp[i - 1] + dp[i - 2];
    return dp[N];
}
```
