### ISSUE TITLE
Suggestions on Monotonic Queue article

### ISSUE THREAD

**Issue by liujiajun** [labuladong/fucking-algorithm#422]
Thanks for the [amazing read](https://labuladong.gitbook.io/algo/shu-ju-jie-gou-xi-lie/dan-tiao-dui-lie) on monotonic queues. While the article is insightful and nicely orginaized, it might be helpful if the part on the properties of monotonic queue and its implementation could be elaborated. For example:
- Why monotonic queues can't report its front element. i.e. no `top()` operation
- Alternative implementations of monotonic queue
- Other problems that can be solved with monotonic queue DS

Using English because Chinese input is not available on my laptop right now.

**Comment by labuladong** [comment]
很好，你可以提相关 pr
