### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by kangniliu** [labuladong/fucking-algorithm#430]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/动态规划之博弈问题](https://labuladong.github.io/ebook/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E4%B9%8B%E5%8D%9A%E5%BC%88%E9%97%AE%E9%A2%98.html
)

问题描述：
dong哥你在动态规划之博弈问题里写了：

> 所以说算法不能简单的一行一行遍历 dp 数组，而要斜着遍历数组

请问为什么不可以用 【从下往上&从左往右】 遍历呢？

`

        for (int i = n-1;i>=0;i--) {
            for (int j = i+1;j<=n-1;j++) {
               //...
            }
        }
`

请大佬不吝赐教！感谢dong哥的分享！！

**Comment by labuladong** [comment]
当然可以！只不过我没写而已，你可以自己试下~
