### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by MilesTin** [labuladong/fucking-algorithm#431]
bug + 经典动态规划：高楼扔鸡蛋（进阶篇）

你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/高楼扔鸡蛋进阶.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E9%AB%98%E6%A5%BC%E6%89%94%E9%B8%A1%E8%9B%8B%E8%BF%9B%E9%98%B6.md)

问题描述：
还可以再优化项
博主，我认真看懂了你的文章，但我觉得最后已经不可以再优化了,因为转移方程为dp[k][m] = dp[k][m - 1] + dp[k - 1][m - 1] + 1;
m是不能用二分，依赖于m-1的dp值，KNlogn算法之所以可以用二分优化，是因为dp[k][n]已经使用O(KN)算出来了。
leetcode数学法其实是你的O（KN）方法，其中N<=logk(N)

**Comment by labuladong** [comment]
数学方法我也没有仔细研究过，你可以自行研究一下
