### ISSUE TITLE
为什么现在都要在公众号里面看了Q_Q

### ISSUE THREAD

**Issue by zawinglee** [labuladong/fucking-algorithm#432]
我可能大概也猜到你这样做的意思(最大原因肯定跟格式没关系), 可是如果想有时候打开网页浏览一下复习一下, 去公众号或者去pdf看没网页里面随意切换快速浏览来的方便和快捷..好难受啊..

**Comment by labuladong** [comment]
好的，我优化一下

**Comment by QCHighing** [comment]
PDF和网页内容总是让转到公众号去阅读，这的确是一种引流手段，但并不是宣称的格式原因。我作为一个免费受益者提要求不合适，但这一点很让人难受，就0-1背包问题，我去找了四五次了。

**Comment by zawinglee** [comment]
赞同…在公众号里面除非这篇文章你被推送过，要不然搜索这个文章真的难上加难…更不要说在电脑微信了…以前我是这个仓库的脑残粉…现在逐渐不喜欢开了…我理解东哥的意思，可是如果有更好的方法的话希望不要用这种方式…而且“格式原因”看着有点中国式😂

**Comment by labuladong** [comment]
谢谢两位的理性的评论，这里面有很多现实的问题，如果有更好的办法，我肯定会做的。
