### ISSUE TITLE
bug + 双指针一文代码中存在bug

### ISSUE THREAD

**Issue by wucong9827** [labuladong/fucking-algorithm#435]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/双指针技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%8F%8C%E6%8C%87%E9%92%88%E6%8A%80%E5%B7%A7.md)

问题描述：第2点（已知链表中含有环，返回这个环的起始位置）代码在leetcode提交时有一个用例无法通过

```java
ListNode detectCycle(ListNode head) {
    ListNode fast, slow;
    fast = slow = head;
    while (fast != null && fast.next != null) {
        fast = fast.next.next;
        slow = slow.next;
        if (fast == slow) break;
    }
    // 上面的代码类似 hasCycle 函数
    slow = head;
    while (slow != fast) {
        fast = fast.next;
        slow = slow.next;
    }
    return slow;
}
```
<img src="https://picabstract-preview-ftn.weiyun.com/ftn_pic_abs_v3/50d042d5a02b4ec56fb5f07804ee1269d7ad761c7459d9a46e4f36395c6a825abb8a0dac6655595bfb7a093ed28d2eb2?pictype=scale&from=30113&version=3.3.3.3&uin=919402566&fname=5F7AAABE-8564-466C-AA33-720EB0B62F44.png&size=750"/>

**Comment by lemonade117** [comment]
我提交也是第一个用例测试不通过，请问问题在哪啊

**Comment by wucong9827** [comment]
> 我提交也是第一个用例测试不通过，请问问题在哪啊

问题在循环条件，为一个节点时无法进入判断，且第二个循环也无法进入，默认就输出为头节点了。可以调整下代码就行了。
```java
  while (true) {
        if (fast == null || fast.next == null) return null;
        fast = fast.next.next;
        slow = slow.next;
        if (fast == slow) break;
    }
```

**Comment by lemonade117** [comment]
> > 我提交也是第一个用例测试不通过，请问问题在哪啊
> 
> 问题在循环条件，为一个节点时无法进入判断，且第二个循环也无法进入，默认就输出为头节点了。可以调整下代码就行了。
> 
> ```java
>   while (true) {
>         if (fast == null || fast.next == null) return null;
>         fast = fast.next.next;
>         slow = slow.next;
>         if (fast == slow) break;
>     }
> ```

按你的方法解决了~谢谢

**Comment by labuladong** [comment]
少了些细节问题，已修复~
