### ISSUE TITLE
bug 算法思维系列/二分查找详解的逻辑统一部分有错误

### ISSUE THREAD

**Issue by wizcheu** [labuladong/fucking-algorithm#436]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/抢房子.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE%E8%AF%A6%E8%A7%A3.md)

问题描述：

第三个，寻找右侧边界的二分查找伪思想最后一句“**所以最后无论返回 left 还是 right，必须减一**”存在错误，不需要减一吧，而且后面的模板代码中也未减一。

**Comment by drcege** [comment]
你没仔细看啊，这个伪思想说的是左闭右开的写法，下面的代码是统一后的闭区间的写法

**Comment by labuladong** [comment]
感谢指出，其实这里说的不是统一的代码模板，我稍微改一下措辞~
