### ISSUE TITLE
Spelling problem in linuxshell.md

### ISSUE THREAD

**Issue by ycollet** [labuladong/fucking-algorithm#443]
In the file linuxshell.md, "nohub" is presented as a command to start a process in detached mode.
This command is "nohup" and not "nohub".

**Comment by amycruz97** [comment]
can I fix it

**Comment by ycollet** [comment]
Go !

**Comment by amycruz97** [comment]
i dont think there is an error there. i cloned the repo but cant find it

**Comment by amycruz97** [comment]
because i am seeing nohup

**Comment by ycollet** [comment]
I checked: the problem is only in the english version:
https://github.com/labuladong/fucking-algorithm/blob/english/common_knowledge/linuxshell.md

**Comment by amycruz97** [comment]
pls i am confused on the repo to clone
https://github.com/amycruz97/fucking-algorithm.git

or the clone link provided in the readme
git clone --depth 1  --branch english https://github.com/labuladong/fucking-algorithm.git


d first one doesnt come out in english too

**Comment by krishnaanaril** [comment]
@ycollet I fixed the issue and created a PR. 
@amycruz97 You need to clone the first one and switch branch to 'english'
