### ISSUE TITLE
linuxProcess.md: typo in image

### ISSUE THREAD

**Issue by fidelbc** [labuladong/fucking-algorithm#446]
The [image](https://github.com/labuladong/fucking-algorithm/blob/english/pictures/linuxProcess/8.jpg) describing the shared resources in a process and a thread contains a typo. Top right label should be "thread" instead of "child process".

Relevant section in [linuxProcess.md](https://github.com/labuladong/fucking-algorithm/blob/english/common_knowledge/linuxProcess.md#%E4%B8%89what-is-a-thread).

**Comment by labuladong** [comment]
thanks, you can pull request to fix it
