### ISSUE TITLE
translate 技术/linux进程.md

### ISSUE THREAD

**Issue by sinjoywong** [labuladong/fucking-algorithm#45]
我将开始翻译如下文章（点击可查看目标文章）：

[技术/linux进程.md](https://github.com/labuladong/fucking-algorithm/blob/master/技术/linux进程.md)

我准备将它翻译成：**英文**

**预计 7 天内翻译完成**，若由于种种原因，规定时间已过但此 issue 还未提交 pull request，则此 issue 自动失效。如果你愿意，你可以新开一个 issue 接替我的工作翻译这篇文章。

**Comment by Seaworth** [comment]
这篇文章，已经开了一个[issues 29](https://github.com/labuladong/fucking-algorithm/issues/29)了，可以换一篇文章，避免重复翻译 @sinjoywong

**Comment by labuladong** [comment]
重复工作，请更换或提交【等待翻译】issue
