### ISSUE TITLE
bug 凑零钱问题不符合最优子结构？

### ISSUE THREAD

**Issue by Sicmatr1x** [labuladong/fucking-algorithm#451]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/动态规划详解进阶.md](https://github.com/labuladong/fucking-algorithm/blob/master/动态规划系列/动态规划详解进阶.md)

问题描述：

根据原文描述：

> 回到凑零钱问题，为什么说它符合最优子结构呢？比如你想求 amount = 11 时的最少硬币数（原问题），如果你知道凑出 amount = 10 的最少硬币数（子问题），你只需要把子问题的答案加一（再选一枚面值为 1 的硬币）就是原问题的答案，因为硬币的数量是没有限制的，子问题之间没有相互制，是互相独立的。

可以尝试构造例子：若k=3, 面值分别为 1，5，6，总金额 amount = 11。按照10+1来算需要5+5+1共计3枚硬币，而更优的是5+6直接就是11了需要2枚硬币。子问题之间有相互制约，所以这个凑零钱问题不符合最优子结构。

**Comment by labuladong** [comment]
看下公众号旧文《动态规划答疑篇》，好好复习下什么是最优子结构
