### ISSUE TITLE
bug 滑动窗口框架最小覆盖子串问题判断逻辑的不足

### ISSUE THREAD

**Issue by scarydemon2** [labuladong/fucking-algorithm#452]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/滑动窗口技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3%E6%8A%80%E5%B7%A7.md)

问题描述：
    // window 中的字符串已符合 needs 的要求了
    while (match == needs.size()) {
        // 更新结果 res
        res = minLen(res, window);
        char c2 = s[left];
        if (needs.count(c2)) {
            window[c2]--; // 移出 window
            **if (window[c2] < needs[c2])**
                // 字符 c2 出现次数不再符合要求
                match--;
        }
        left++;
    }
在判断窗口左边是否满足条件的时候，**if (window[c2] < needs[c2])**逻辑应该为window[c2]==needs[c2]-1，因为可能会出现s左侧出现相同的字母，每次在不满足条件的时候都会减少一次match，然而match数量对应字母的种类，而不是字母数量,，修改后可以提交通过。

**Comment by labuladong** [comment]
不修改就过不了吗？我这边都是通过测试的

**Comment by labuladong** [comment]
我没太理解你说的意思，要不你说个反例出来？有问题的话我也好改。

**Comment by scarydemon2** [comment]
是我理解错了。。我关掉这个issue了
