### ISSUE TITLE
labuladong啥意思

### ISSUE THREAD

**Issue by MiKKiYang** [labuladong/fucking-algorithm#453]
labuladong啥意思

**Comment by kingname** [comment]
拉不拉东

**Comment by labuladong** [comment]
有一天我看到一条拉布拉多犬，于是一拍脑袋起了这个笔名……

**Comment by workhard1010** [comment]
我就感觉和拉布拉多好像，，，以为你养了只




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labuladong/fucking-algorithm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 上午9:54
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] labuladong啥意思 (#453)





 
有一天我看到一条拉布拉多犬，于是一拍脑袋起了这个笔名……

**Comment by labuladong** [comment]
没有，为了让大家容易记住我🤣

**Comment by mao720** [comment]
货拉拉拉不拉拉布拉东
