### ISSUE TITLE
bug twoSum问题的核心思想中优化后的Find查找时间复杂度不是O(1)，是O(n)

### ISSUE THREAD

**Issue by wogaokui** [labuladong/fucking-algorithm#458]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/抢房子.md](https://github.com/labuladong/fucking-algorithm/blob/master/算法思维系列/twoSum问题的核心思想.md)

问题描述：
![image](https://user-images.githubusercontent.com/5170108/93655932-3cf5da80-fa59-11ea-8e4a-a3e957076449.png)

这里其实是使用了ArrayList来存储结果集合nums，查找的contains的算法复杂度为O(n），而不是O(1),正确的 是应该用一个hash集合来存储 。

**Comment by labuladong** [comment]
注意看哦，是对 `sum` 使用 contains 方法，不是对 `nums` 使用 contains 方法~
