### ISSUE TITLE
股票第一题关于k的优化

### ISSUE THREAD

**Issue by qianyuyu** [labuladong/fucking-algorithm#459]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/动态规划系列/团灭股票问题.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%9B%A2%E7%81%AD%E8%82%A1%E7%A5%A8%E9%97%AE%E9%A2%98.md)

问题描述：

文章有说过

> 这个解释应该很清楚了，如果 buy，就要从利润中减去 prices[i]，如果 sell，就要给利润增加 prices[i]。今天的最大利润就是这两种可能选择中较大的那个。而且注意 k 的限制，我们在选择 buy 的时候，把 k 减小了 1，很好理解吧，当然你也可以在 sell 的时候减 1，一样的。

意味伪代码可以这么改写么？
`dp[i][k][0] = max(dp[i-1][k][0], dp[i-1][k-1][1] + prices[i]) `
`dp[i][k][1] = max(dp[i-1][k][1], dp[i-1][k][0] - prices[i])`

这样就是在卖股票的时候减一次，
那这时候按照第一题思路是

`dp[i][1][0] = max(dp[i-1][1][0], dp[i-1][0][1] + prices[i])  `
                    `= max(dp[i-1][1][0], -Inf+prices[i])  `
`dp[i][1][1] = max(dp[i-1][1][1], dp[i-1][1][0] - prices[i])   `
            

从数学角度来说dp[i][1][0]永远是0呀？

**Comment by nanjixiong218** [comment]
感觉这篇文章确实没有说清楚k的含义，只是一笔带过『很好理解吧』，其实就这个k最难理解，它如何进行抽象，它的影响和变化依据？想不清楚

**Comment by lifei6671** [comment]
> 感觉这篇文章确实没有说清楚k的含义，只是一笔带过『很好理解吧』，其实就这个k最难理解，它如何进行抽象，它的影响和变化依据？想不清楚

确实是，我这算法渣渣看我了，还是一头雾水。😂

**Comment by ZLOVE320483** [comment]
public int maxProfit_k_any(int max_k, int[] prices) {
        int n = prices.length;
        if (max_k > n / 2)
            return maxProfit_k_inf(prices);

        int[][][] dp = new int[n][max_k + 1][2];
        for (int i = 0; i < n; i++)
            for (int k = max_k; k >= 1; k--) {
                if (i - 1 == -1) {
                    // 对边界case的处理
                    dp[i][k][0] = 0;
                    dp[i][k][1] = Integer.MIN_VALUE;
                    continue;
                }
                dp[i][k][0] = Math.max(dp[i-1][k][0], dp[i-1][k][1] + prices[i]);
                dp[i][k][1] = Math.max(dp[i-1][k][1], dp[i-1][k-1][0] - prices[i]);
            }
        return dp[n - 1][max_k][0];
    }

    private int maxProfit_k_inf(int[] prices) {
        int n = prices.length;
        int dp_i_0 = 0, dp_i_1 = Integer.MIN_VALUE;
        for (int i = 0; i < n; i++) {
            int temp = dp_i_0;
            dp_i_0 = Math.max(dp_i_0, dp_i_1 + prices[i]);
            dp_i_1 = Math.max(dp_i_1, temp - prices[i]);
        }
        return dp_i_0;
    }

大佬好，对于k是任意值的股票问题，我这样处理的边界case，但是发现并不能通过测试，请问是我哪里处理的有问题吗？

**Comment by 251205668** [comment]
确实，股票第三题好像代码有点问题吗，我用js写也通不过

**Comment by voidspiral** [comment]
哦草。。。你不是真觉得他能看懂吧

> ```
> public int maxProfit_k_any(int max_k, int[] prices) {
>     int n = prices.length;
>     if (max_k > n / 2)
>         return maxProfit_k_inf(prices);
>     int[][][] dp = new int[n][max_k + 1][2];
>     for (int i = 0; i < n; i++)
>         for (int k = max_k; k >= 1; k--) {
>             if (i - 1 == -1) {
>                 // 对边界case的处理
>                 dp[i][k][0] = 0;
>                 dp[i][k][1] = Integer.MIN_VALUE;
>                 continue;
>             }
>             dp[i][k][0] = Math.max(dp[i-1][k][0], dp[i-1][k][1] + prices[i]);
>             dp[i][k][1] = Math.max(dp[i-1][k][1], dp[i-1][k-1][0] - prices[i]);
>         }
>     return dp[n - 1][max_k][0];
> }
> 
> private int maxProfit_k_inf(int[] prices) {
>     int n = prices.length;
>     int dp_i_0 = 0, dp_i_1 = Integer.MIN_VALUE;
>     for (int i = 0; i < n; i++) {
>         int temp = dp_i_0;
>         dp_i_0 = Math.max(dp_i_0, dp_i_1 + prices[i]);
>         dp_i_1 = Math.max(dp_i_1, temp - prices[i]);
>     }
>     return dp_i_0;
> }
> ```
> 
> 大佬好，对于k是任意值的股票问题，我这样处理的边界case，但是发现并不能通过测试，请问是我哪里处理的有问题吗？

他看不懂。。
