### ISSUE TITLE
GitBook替换为VuePress

### ISSUE THREAD

**Issue by JackyAndroid** [labuladong/fucking-algorithm#460]
GitBook加载慢，文档结构老旧，扩展性差，建议替换为VuePress。

为什么Vue不用GitBook（引用自https://vuepress.vuejs.org/zh/guide/#features）：
> GitBook
我们的子项目文档一直都在使用 GitBook。GitBook 最大的问题在于当文件很多时，每次编辑后的重新加载时间长得令人无法忍受。它的默认主题导航结构也比较有限制性，并且，主题系统也不是 Vue 驱动的。GitBook 背后的团队如今也更专注于将其打造为一个商业产品而不是开源工具。

**Comment by labuladong** [comment]
会考虑的
