### ISSUE TITLE
gitbook

### ISSUE THREAD

**Issue by sakurasakura1996** [labuladong/fucking-algorithm#462]
十分感谢您的工作，问题是这样的，我喜欢使用语雀来记录笔记，然后我发现可以通过导入GitBook来直接生成文档，所以想问，是否可以提供GitBook版本的资源。如果不行，也还是十分感谢，因为这个资源对于大多数人来说都很有用处。

**Comment by labuladong** [comment]
公众号后台回复 pdf 可以下载 PDF 版本，不知道是否对你有用？
