### ISSUE TITLE
请教一个问题[动态规划-正则篇]

### ISSUE THREAD

**Issue by duringnone** [labuladong/fucking-algorithm#465]
hello,东哥,叨扰了, 在学习动态规划篇-正则篇章时,有一个疑惑,请教下,原文代码如下:
def isMatch(text, pattern) -> bool:
    if not pattern: return not text
    first = bool(text) and pattern[0] in {text[0], '.'}
    if len(pattern) >= 2 and pattern[1] == '*':
        return isMatch(text, pattern[2:]) or \
                first and isMatch(text[1:], pattern)
    else:
        return first and isMatch(text[1:], pattern[1:])

个人理解:
def isMatch(text, pattern) -> bool:
    if not pattern: return not text
    first = bool(text) and pattern[0] in {text[0], '.'}
    if len(pattern) >= 2 and pattern[1] == '*':
        return isMatch(text, pattern[2:]) or \
                first or isMatch(text[1:], pattern)
    else:
        return first or isMatch(text[1:], pattern[1:])

我修改后的代码和原文差别:  [左侧原文,右侧我修改的]
    first and isMatch(text[1:], pattern)   =>  first or isMatch(text[1:], pattern)
    return first and isMatch(text[1:], pattern[1:]) => return first or isMatch(text[1:], pattern[1:])
我之所以这么理解的原因和依据: 
  1) 发现 "and" 和 "or" 所导致的结果是完全不同的
   2) "." 和 "*"并列的关系, 二者只需满足其一即可, 故使用or,而非and
希望东哥方便的时候解答一下,谢谢啦

**Comment by labuladong** [comment]
你这个代码这么乱，怎么看……
