### ISSUE TITLE
bug 动态规划阶梯套路框架：dp 数组的迭代解法，临界值 N = 0或1 时 数组越界

### ISSUE THREAD

**Issue by gocpplua** [labuladong/fucking-algorithm#466]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

https://labuladong.gitbook.io/algo/di-ling-zhang-bi-du-xi-lie/dong-tai-gui-hua-xiang-jie-jin-jie

问题描述：

dp 数组的迭代解法，临界值 N = 0或1 时 数组越界

**Comment by labuladong** [comment]
感谢指出，已修改
