### ISSUE TITLE
bug 总感觉你这个洗牌算法有点问题。

### ISSUE THREAD

**Issue by boyalearn** [labuladong/fucking-algorithm#469]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

一次洗牌并不会洗出所有的可能性。示例 1，2，3来说一次洗牌只能得到3,1,2或2,3,1。所以一次洗牌算法要正确得到所有可能的排列并且要使每种情况概率相等。是不是要根据牌的数量来推到洗牌的次数？如对以下代码进行改造

void shuffle(int[] arr) {
    int n = arr.length();
    /******** 区别只有这两行 ********/
    for(int k=0 ;k< m;k++)                //新增  m的值需要通过一个算法来推导循环的次数
    for (int i = 0 ; i < n; i++) {
        // 从 i 到最后随机选一个元素
        int rand = randInt(i, n - 1);
        /*************************/
        swap(arr[i], arr[rand]);
    }
   }                                                      //新增
}

**Comment by labuladong** [comment]
「一次洗牌只能得到3,1,2或2,3,1」，你是怎么得出这个结论的？可以得到所有可能的排列呀？
