### ISSUE TITLE
bug isValidBST有问题

### ISSUE THREAD

**Issue by georgetso** [labuladong/fucking-algorithm#472]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[数据结构系列/二叉搜索树操作集锦.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E7%B3%BB%E5%88%97/%E4%BA%8C%E5%8F%89%E6%90%9C%E7%B4%A2%E6%A0%91%E6%93%8D%E4%BD%9C%E9%9B%86%E9%94%A6.md)

问题描述：

boolean isValidBST(TreeNode root, TreeNode min, TreeNode max) 该函数内部, min/max 从未被赋值, 始终是 null.

**Comment by labuladong** [comment]
不是复制 root 了吗？
