### ISSUE TITLE
bug Gitbook缺少了内容

### ISSUE THREAD

**Issue by mybluedog24** [labuladong/fucking-algorithm#474]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[Gitbook 文章：我写了首诗，把滑动窗口算法算法变成了默写题](https://labuladong.gitbook.io/algo/di-ling-zhang-bi-du-xi-lie-qing-an-shun-xu-yue-du/hua-dong-chuang-kou-ji-qiao-jin-jie)
[Gitbook 文章：一个方法团灭 LeetCode 打家劫舍问题](https://labuladong.gitbook.io/algo/di-ling-zhang-bi-du-xi-lie-qing-an-shun-xu-yue-du/qiang-fang-zi)

问题描述：
~~以上两篇文章的后面都没有了详细的题目讲解，但是Github上的原文是有的。~~
好吧，才看到那行字：
> 本文只能在 labuladong 公众号查看，关注后可直接搜索本站内容

比较困惑的是首页说后续文章只放在公众号/gitbook/知乎，不放Github，但是这两篇Github上的文章比Gitbook的更全。希望可以的话同步到Gitbook，谢谢！

**Comment by labuladong** [comment]
收到
