### ISSUE TITLE
Linux进程描述错误

### ISSUE THREAD

**Issue by Kyle-Kyle** [labuladong/fucking-algorithm#477]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[Linux的进程、线程、文件描述符是什么](https://github.com/labuladong/fucking-algorithm/blob/master/%E6%8A%80%E6%9C%AF/linux%E8%BF%9B%E7%A8%8B.md)

两个问题：
1. 在解释`task->files`的时候，描述上看会让人误认`files`是一个array。其实不然，`files`是对一个task下所有文件的概述。详情如下
~~~
struct files_struct {
  /*
   * read mostly part
   */
	atomic_t count;
	bool resize_in_progress;
	wait_queue_head_t resize_wait;

	struct fdtable __rcu *fdt;
	struct fdtable fdtab;
  /*
   * written part on a separate cache line in SMP
   */
	spinlock_t file_lock ____cacheline_aligned_in_smp;
	unsigned int next_fd;
	unsigned long close_on_exec_init[1];
	unsigned long open_fds_init[1];
	unsigned long full_fds_bits_init[1];
	struct file __rcu * fd_array[NR_OPEN_DEFAULT];
};
~~~
`fd_array`才是存储fd和file信息的array.

2. 在Linux中，虽然`clone`syscall模糊化了process和thread的界限，但是这个界限始终存在。解释上更像是process是一个包含了好多thread的一个壳。在生成process的时候自动往这个壳里放了一个main_thread.
例子挺多的，我列举两个：
a. 一个线程call了exit，该process里的所有的thread全部exit。
b. 在desktop上，一个process里的所有thread是被一起schedule的。详情参照CONFIG_SCHED_AUTOGROUP。

**Comment by labuladong** [comment]
你好，感谢指正，可以直接提交 pr 添加你认为正确的描述~
