### ISSUE TITLE
LRU中赋值覆盖 

### ISSUE THREAD

**Issue by pengbinbin1** [labuladong/fucking-algorithm#479]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[LRU.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97/LRU%E7%AE%97%E6%B3%95.md)

问题描述：
该部分有一个接口 addLast 
 public void addLast(Node x) {
        x.prev = tail.prev;
        x.next = tail;
        tail.prev.next = x;
        tail.prev = x;
        size++;
    }

代码中的倒数第二第三行存在bug  tail.prev = x  会将tail.pre.next=x 的赋值覆盖掉

**Comment by labuladong** [comment]
没有吧，测试过吗？我理解这不是把 `x` 插到 `tail` 之前了吗？

**Comment by pengbinbin1** [comment]
用golang试过，确实会覆盖，搞了一个临时变量保存了一下tail.pre的值，这样结果就对了

**Comment by labuladong** [comment]
听你这么说，是不是没用指针？链表节点都是用指针的哦
