### ISSUE TITLE
translate 高频面试系列/缺失和重复的元素.md

### ISSUE THREAD

**Issue by chrisncao** [labuladong/fucking-algorithm#48]
我已阅读过[翻译组工作流程](https://github.com/labuladong/fucking-algorithm/issues/9)，我没有和其他人的工作产生冗余或冲突。

我已阅读过[翻译要求](https://github.com/labuladong/fucking-algorithm/blob/english/README.md)，我暂时拥有了提交权限，会对此次翻译的质量负责。

我将开始翻译如下文章（点击可查看目标文章）：

[高频面试系列/缺失和重复的元素.md](https://github.com/labuladong/fucking-algorithm/blob/master/高频面试系列/缺失和重复的元素.md)

我对如何翻译此文章已经心中有数，我准备将它翻译成：**英文**

**预计 7 天内翻译完成**，若由于种种原因，规定时间已过但此 issue 还未提交 pull request，则此 issue 自动失效。如果你愿意，你可以新开一个 issue 接替我的工作翻译这篇文章。

**Comment by labuladong** [comment]
**2020/3/1 update: 由于需要借助 Github Trending 推荐这波曝光，英文版需快速完成，所以更改之前的计划，任务不再具有抢占性，issue 中申明的时间不再有效，主仓库会接受最先提交 pull request 的文章，并且会在开头声明翻译者并链接向其 Github 主页**。

详情见 [置顶 issue](https://github.com/labuladong/fucking-algorithm/issues/9)
