### ISSUE TITLE
目录重新归类导致之前的链接失效

### ISSUE THREAD

**Issue by inkydragon** [labuladong/fucking-algorithm#480]
搜索引擎搜到的链接没有设置 301 重定向
例如：
https://labuladong.gitbook.io/algo/shu-ju-jie-gou-xi-lie/sui-ji-ji-he

应该被重定向到 
https://labuladong.gitbook.io/algo/shu-ju-jie-gou-xi-lie/2.5-shou-ba-shou-shua-shu-zu-ti-mu/sui-ji-ji-he

gitbook 的文档里提到可以通过配置文件设置重定向
[Content Configuration - GitBook Documentation](https://docs.gitbook.com/integrations/github/content-configuration#redirects)

例子：[fluentd-docs-gitbook/.gitbook.yaml at 1.0 · fluent/fluentd-docs-gitbook](https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/.gitbook.yaml)
效果： https://docs.fluentd.org/v1.0/articles/support 
---> `https://docs.fluentd.org/quickstart/support`

----

或者也可以考虑使用固定形式的永久链接
+ URL 里只包含标题：`https://labuladong.gitbook.io/algo/sui-ji-ji-he`
+ 标题 + UUID：`https://labuladong.gitbook.io/algo/sui-ji-ji-he-f809b1d5-aabb-4d8f-9de7-0dd4d4aadd47`

**Comment by labuladong** [comment]
哦哦，感谢提醒，这个固定形式的永久链接怎么搞啊，文档里好像没有？
