### ISSUE TITLE
二分查找详解的一点小问题

### ISSUE THREAD

**Issue by Kuangjun-Sunflower** [labuladong/fucking-algorithm#481]
1. `一、寻找一个数（基本的二分搜索）`下`这个场景是最简单的，肯能也是大家最熟悉的`
这个`肯能` 应该是`可能`
2. `while(left < right)` 的终止条件是 `left == right`，写成区间的形式就是 `[left, right]`，
这个区间`[left, right]`，应该是`[right, right]`
还有就是吹爆作者，写的真好，继续学习

**Comment by labuladong** [comment]
感谢指出，已修复~
