### ISSUE TITLE
bug 单调栈 力扣题目链接错误

### ISSUE THREAD

**Issue by littlecry** [labuladong/fucking-algorithm#514]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）

[数据结构系列/单调栈.md](https://github.com/labuladong/fucking-algorithm/blob/master/数据结构系列/单调栈.md)

问题描述
用单调栈解决的问题
第23行
[1118.一月有多少天](https://leetcode-cn.com/problems/number-of-days-in-a-month)
应该是
[739. Daily Temperatures] (https://leetcode.com/problems/daily-temperatures/)

同样，第85行
“力扣第 1118 题「一月有多少天」：”
应该为
“力扣第 739 题「每日温度」”

**Comment by littlecry** [comment]
另外提供了Java 版本的leetcode 739 解法https://github.com/labuladong/fucking-algorithm/pull/512/commits/91e56f8727f7d5ef1ec5bd1da9944f89592fd196

**Comment by labuladong** [comment]
感谢指出，已修复，Java 代码请直接给出 pr 链接，我 merge 进去~

**Comment by littlecry** [comment]
> 感谢指出，已修复，Java 代码请直接给出 pr 链接，我 merge 进去~

https://github.com/labuladong/fucking-algorithm/commit/91e56f8727f7d5ef1ec5bd1da9944f89592fd196
