### ISSUE TITLE
葡萄不见了😂

### ISSUE THREAD

**Issue by zhengpj95** [labuladong/fucking-algorithm#521]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/滑动窗口技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/算法思维系列/滑动窗口技巧.md)

问题描述：

开头推荐的 【东哥吃葡萄时竟然吃出一道算法题！】链接不对！！

**Comment by labuladong** [comment]
已修复
