### ISSUE TITLE
提交算法的形式有点不对劲

### ISSUE THREAD

**Issue by lixiandea** [labuladong/fucking-algorithm#589]
多人同时提交pr，有的时候会在同一个文件里面产生修改，导致刚开始提交时通过了冲突检测，后面当管理员通过其中一个pr，别的pr会同时因为冲突不得不关闭。

**Comment by lixiandea** [comment]
这算是pr的多线程冲突吗？

**Comment by labuladong** [comment]
没关系，我会来解决冲突的
