### ISSUE TITLE
bug 双指针技巧总结链接错误

### ISSUE THREAD

**Issue by antbaobao** [labuladong/fucking-algorithm#598]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[双指针技巧总结](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E5%8F%8C%E6%8C%87%E9%92%88%E6%8A%80%E5%B7%A7.md)

问题描述：

167.两数之和 II - 输入有序数组链接有误

**Comment by labuladong** [comment]
感谢指出，已修复~
