### ISSUE TITLE
想知道该仓库是否为作者自己写的

### ISSUE THREAD

**Issue by sinnosong** [labuladong/fucking-algorithm#605]
今天搜索滑动窗口算法时偶然发现了这篇文章https://blog.csdn.net/Dby_freedom/article/details/89066140

**Comment by labuladong** [comment]
我在公众号 [滑动窗口算法详解](https://mp.weixin.qq.com/s?__biz=MzAxODQxMDM0Mw==&mid=2247484504&idx=1&sn=5ecbab87e42033cc0a62b635cc436977&chksm=9bd7fa50aca07346a3ffa6be6fccc445968c162af9532fa9c6304eaab2e3a1b79a4bbe758c0a&token=570522932&lang=zh_CN#rd) 先发的，你这个博客链接直接把我的图拿去用了。
