### ISSUE TITLE
Gitbook的SLUG能变成中文吗

### ISSUE THREAD

**Issue by TWDH** [labuladong/fucking-algorithm#611]
哈喽，我自己也在gitbook上面做笔记。但是每次同步到github上面目录总是这样的（1.-er-cha-shu-de-qian-xu-bian-li-144.md）请问怎么写的时候在gitbook上面SLUG改成中文？谢谢
或者能不能告诉我啥其他办法可以解决这个问题呢~比如您是怎么干的

**Comment by labuladong** [comment]
没有办法，我就是默认的
