### ISSUE TITLE
bug 二分查找详解 算法未考虑完全

### ISSUE THREAD

**Issue by wenscarl** [labuladong/fucking-algorithm#612]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/二分查找详解.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E7%AE%97%E6%B3%95%E6%80%9D%E7%BB%B4%E7%B3%BB%E5%88%97/%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE%E8%AF%A6%E8%A7%A3.md)

问题描述：在`right=length(); (left<right)` 的情况下，如果你非要用 while(left < right) 也可以，我们已经知道了出错的原因，就打个补丁好了：
`    //...
    while(left < right) {
        // ...
    }
    return nums[left] == target ? left : -1;`

这里漏掉了一个情况，`nums.length()==1 并且`nums[0]!=target`, 这时候left or right 会越界。 需要排除这种情况。

**Comment by liz11111** [comment]
class Solution:
          def findPeakElement(self, nums: List[int]) -> int:
              l,r=0,len(nums)-1
              while l<r:
                  m=(l+r)//2
                  if nums[m]>nums[m+1]:
                      r=m
                  else:
                      l=m+1
              return l

想请问下这个情况，没有在二分查找中解释呀
