### ISSUE TITLE
生活中的算法-发票报销

### ISSUE THREAD

**Issue by Ck-Coffee** [labuladong/fucking-algorithm#614]
目前有一个报销需求（固定报销额度），需要用到已有发票（金额不一）,但为了避免发票金额浪费，请给出一个最接近报销额度的方案

 * <p>
 * 注意：报销方案中的发票总金额 必须大于等于 报销额度
 * 给定的发票列表的总金额一定大于 报销额度
 * ex1.
 * 输入: 发票金额: 10 20 30  额度:40
 * 输出: 10 30
 * <p>
 * ex2.
 * 输入: 发票金额: 12.1 23.5 43.1 22.2 额度:50
 * 输出: 12.1 43.1

用的回溯 感觉复杂度太高了，有没有好的思路啊0.0

    public List<Double> appropriateReimbursementPlan(double[] invoiceMoneys, double reimbursementLimit) {
        List<Double> plan = Lists.newArrayList();
        List<Double> tempPlan = Lists.newArrayList();
        doProcess(plan, invoiceMoneys, reimbursementLimit, 0, tempPlan, 0, Double.MAX_VALUE);
        return plan;
    }

    private void doProcess(List<Double> resultPlan, double[] invoiceMoneys, double reimbursementLimit,
                           int index, List<Double> tempPlan, double currTotalMoney, double currMinMoney) {
        if (currTotalMoney >= reimbursementLimit && currTotalMoney < currMinMoney ) {
            currMinMoney = currTotalMoney;
            resultPlan.clear();
            for (Double d : tempPlan) {
                resultPlan.add(d);
            }
        }
        for (int i = index; i < invoiceMoneys.length; i++) {
            tempPlan.add(invoiceMoneys[index]);
            doProcess(resultPlan, invoiceMoneys, reimbursementLimit, i + 1, tempPlan,
                    currTotalMoney + invoiceMoneys[index], currMinMoney);
            tempPlan.remove(tempPlan.size() - 1);
        }

    }

**Comment by shimachao** [comment]
我司一般的报销发票分为交通还是餐饮。我一般会合计一下哪些项目使用交通发票，哪些使用餐饮发票

**Comment by wxzwsj197950** [comment]
至少可以剪枝下，大于currMinmoney就不要递归了

**Comment by labuladong** [comment]
这不就是典型的背包问题吗？
