### ISSUE TITLE
bug 公众号中的“滑动窗口”一文中的bug

### ISSUE THREAD

**Issue by zhangxiao123qqq** [labuladong/fucking-algorithm#635]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[滑动窗口-字符串排列](https://mp.weixin.qq.com/s?__biz=MzAxODQxMDM0Mw==&mid=2247485141&idx=1&sn=0e4583ad935e76e9a3f6793792e60734&chksm=9bd7f8ddaca071cbb7570b2433290e5e2628d20473022a5517271de6d6e50783961bebc3dd3b&scene=21#wechat_redirect)
![1609813480(1)](https://user-images.githubusercontent.com/40785709/103599737-cc5bc680-4f40-11eb-85d9-70deda0d5bfb.png)
```
//相当给你一个S和一个T，请问你S中是否存在一个子串，包含T中所有字符且不包含其他字符？
 // 判断左侧窗口是否要收缩
        while (right - left >= t.size()) {
            // 在这里判断是否找到了合法的子串
            if (valid == need.size())
                return true;
            char d = s[left];
            left++;
            // 进行窗口内数据的一系列更新
            if (need.count(d)) {
                if (window[d] == need[d])
                    valid--;
                window[d]--;
            }
        }
    }
```

问题描述：
  这里当窗口大小还不确定的情况下，就判断valid是否满足，是不是不恰当的，应该是只有 len==T.len()才可以判断吧？ 我看到git仓中并没有这个案例，也是因为这个公众号中的bug吗？
 通过学习到了很多！感谢！

**Comment by zhangxiao123qqq** [comment]
请问 上述代码中，`while`中的条件 `>=`与`==`是不是一样的？ 因为应该不会存在`>`的情况？

**Comment by casablancaml** [comment]
其实这个题目和最小覆盖子串及其相似，可以修改最少的代码就能得到正确的code。关键点在于，缩小窗口的第一条件是什么？
如果第一条件是valid即匹配个数等于target串中的相异字符数，那么检查完长度匹配后才能缩小窗口、扣除那个将要移出窗口的旧字符对应的match数量、++left等一系列操作，检查长度只能是第二条件。

    bool checkInclusion(string s1, string s2) {
        const int S_TOTAL_LENGTH = s2.length();
        const int T_TOTAL_LENGTH = s1.length();
        if (T_TOTAL_LENGTH == 0 || T_TOTAL_LENGTH > S_TOTAL_LENGTH) {
            return false;
        }

        unordered_map<char, int> window;
        unordered_map<char, int> needs;
        for (int i = 0; i < T_TOTAL_LENGTH; i++) {
            ++needs[s1[i]];
        }

        int  matchCnt = 0;
        int  left = 0, right = 0;

        while (right < S_TOTAL_LENGTH) {
            char c1 = s2[right];
            if (needs.count(c1) != 0 && ++window[c1] == needs[c1]) {
                ++matchCnt;
            }
            ++right;

            while (matchCnt == needs.size()) {
                if (right - left == T_TOTAL_LENGTH) {   // 同时，长度等于 s1
                    return true;         // 根据题目意图，此处直接 return true;即可
                }
                char c2 = s2[left];
                if (needs.count(c2) != 0 && --window[c2] < needs[c2]) {
                    --matchCnt;
                }
                ++left;
            }
        }

        return false;
    }


相反如果检查长度是第一条件，那么就要变换一下扣减条件：

        // 判断左侧窗口是否要收缩
        while (right - left >= t.size()) {
            // 在这里判断是否找到了合法的子串
            if (valid == need.size()) {
                return true;
            }
            char d = s[left];
            // 进行窗口内数据的一系列更新
            if (need.count(d) && window[d]-- == need[d]) {    // 这里是==而不是<
                valid--;
            }
            left++;
        }
