### ISSUE TITLE
滑动窗口模板一些建议

### ISSUE THREAD

**Issue by huangbxaaa** [labuladong/fucking-algorithm#655]
今天看了滑动窗口这篇文章，受益匪浅。
根据文章的三个例子，我感觉模板可以稍微修改一下，像这样：

第一种：（对应例1，例2）
```java
int left = 0, right = 0;

while (right < s.size()) {
    // 非法 -> 合法
    window.add(s[right]);
    right++;
    
    // 合法 -> 非法
    while (valid) {
        // 更新res
        window.remove(s[left]);
        left++;
    }
}

```

第二种：（对应例3）
```java
int left = 0, right = 0;

while (right < s.size()) {
    // 合法 -> 非法
    window.add(s[right]);
    right++;
    
    // 非法 -> 合法
    while (!valid) {
        window.remove(s[left]);
        left++;
    }

    // 更新res
}
```

或许这样更好一些？
才疏学浅，如有错误，欢迎指正。

**Comment by labuladong** [comment]
不错的建议，同时祝你春节快乐🎉🎉


------------------ 原始邮件 ------------------
发件人: hbx666 <notifications@github.com&gt;
发送时间: 2021年2月16日 11:19
收件人: labuladong/fucking-algorithm <fucking-algorithm@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[labuladong/fucking-algorithm] 滑动窗口模板一些建议 (#655)





 
今天看了滑动窗口这篇文章，受益匪浅。
 根据文章的三个例子，我感觉模板可以稍微修改一下，像这样：
 
第一种：（对应例1，例2）
 int left = 0, right = 0; while (right < s.size()) {     // 非法 -&gt; 合法     window.add(s[right]);     right++;          // 合法 -&gt; 非法     while (valid) {         // 更新res         window.remove(s[left]);         left++;     } } 
 
第二种：（对应例3）
 int left = 0, right = 0; while (right < s.size()) {     // 合法 -&gt; 非法     window.add(s[right]);     right++;          // 非法 -&gt; 合法     while (!valid) {         window.remove(s[left]);         left++;     }     // 更新res }
 
或许这样更好一些？
 才疏学浅，如有错误，欢迎指正。
