### ISSUE TITLE
gitbook 上的一个跳转链接打不开

### ISSUE THREAD

**Issue by zhangxiann** [labuladong/fucking-algorithm#660]
gitbook 上下图的链接打不开。
[动态规划设计：最长递增子序列](https://github.com/labuladong/algo/tree/892ca1bf8c91e1f0f9b097f528c8decee7f85353/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E8%AE%BE%E8%AE%A1%EF%BC%9A%E6%9C%80%E9%95%BF%E9%80%92%E5%A2%9E%E5%AD%90%E5%BA%8F%E5%88%97.md)
![image](https://user-images.githubusercontent.com/12131262/109243437-e36bb600-7817-11eb-96aa-74563c9ffac7.png)

**Comment by labuladong** [comment]
已修复

**Comment by zhangxiann** [comment]
赞
