### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by junhaideng** [labuladong/fucking-algorithm#668]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[算法思维系列/双指针技巧.md](https://github.com/labuladong/fucking-algorithm/blob/master/算法思维系列/双指针技巧.md)

问题描述：

如下内容描述错误：
```
当链表的长度是奇数时，slow 恰巧停在中点位置；如果长度是偶数，slow 最终的位置是中间偏右：
```
应为：
```
当链表的长度是奇数时，slow 恰巧停在中点位置；如果长度是偶数，slow 最终的位置是中间偏左：
```
比如链表为 0, 1, 2, 3 时，slow为1，处于中间位置偏左，而非偏右

**Comment by brucecat** [comment]
好的，收到！

**Comment by brucecat** [comment]
您的邮件已收到！
