### ISSUE TITLE
bug left_bound 二分查找函数校验不过

### ISSUE THREAD

**Issue by wangzhenyu32** [labuladong/fucking-algorithm#681]
#include <iostream>
#include <vector>

int left_bound(std::vector<int>& nums, int target) {
    int left = 0, right = nums.size() - 1;
    // 搜索区间为 [left, right]
    while (left <= right) {
        int mid = left + (right - left) / 2;
        if (nums[mid] < target) {
            // 搜索区间变为 [mid+1, right]
            left = mid + 1;
        } else if (nums[mid] > target) {
            // 搜索区间变为 [left, mid-1]
            right = mid - 1;
        } else if (nums[mid] == target) {
            // 收缩右侧边界
            right = mid - 1;
        }
    }
    // 检查出界情况
    if (left >= nums.size() || nums[left] != target)
        return -1;
    return left;
}

int main(){
   std::vector<int> a = {1,2,4,5,6};
   std::cout << left_bound(a,3);
}

return the result is -1

**Comment by kaka2634** [comment]
因为nums[left] != target 是返回 -1 啊

**Comment by zhoyifan** [comment]
我也发现这个问题了。搜索区间为 [left, right]的左侧边界的二分查找，最后没有”return left - 1“。如果最后结果减1就行了？
