### ISSUE TITLE
凑零钱问题/暴力递归

### ISSUE THREAD

**Issue by coki230** [labuladong/fucking-algorithm#708]
你好，我发现如下文章有可能 bug（也可能是我理解错误）：

[凑零钱问题/暴力递归](https://labuladong.gitee.io/algo/1/3/)

问题描述：

比如你想求 amount = 11 时的最少硬币数（原问题），如果你知道凑出 amount = 10 的最少硬币数（子问题），你只需要把子问题的答案加一（再选一枚面值为 1 的硬币）就是原问题的答案。
上面的是原文，但是我个人不太理解，比如amount = 15时的最少硬币数，如果我凑出 amount = 14 的最少硬币数为
5+5+2+2；数量为4。但是子问题加一为５.不是有问题的答案，原问题最少应该是５＋５＋５数量是三

**Comment by jasonleecode** [comment]
good job
