### ISSUE TITLE
力扣刷题辅助插件 bug 反馈区

### ISSUE THREAD

**Issue by L0veRamen** [labuladong/fucking-algorithm#709]
Edge游览器读取不出新版本,有个issue error[](ur
![issue](https://user-images.githubusercontent.com/53376484/141384645-6e21d156-e09c-4661-bc05-2ebedc823ea1.png)
l)

**Comment by labuladong** [comment]
我目前没有条件测试 Edge 浏览器的兼容性，请你把出现的问题发布在 [这里](https://github.com/labuladong/fucking-algorithm/discussions/704)，看看是否有其他人遇到同样的问题。
