### ISSUE TITLE
力扣刷题辅助插件 bug 反馈区

### ISSUE THREAD

**Issue by junjie-code200** [labuladong/fucking-algorithm#712]
windows 10，chrome版本 96.0.4664.45（正式版本） （64 位）,点击leetcode题目的题解按钮直接打开的是labaladong网站，而不是小窗展示，不知道是啥原因？如截图
![1637415059(2)](https://user-images.githubusercontent.com/82194073/142728543-b7394ecd-1e36-4fc3-8ac8-035e78f2a088.png)
![1637415059](https://user-images.githubusercontent.com/82194073/142728546-63440e49-129f-463f-a436-40b4616f4eb0.png)
![1637415853(1)](https://user-images.githubusercontent.com/82194073/142728595-9bdf7380-5e50-48f5-8970-03c19489c5ab.png)
：

**Comment by labuladong** [comment]
没问题，这是预期效果。你说的小窗展示按钮在题目详情页才有。
