### ISSUE TITLE
leetcode helper google extensin提示本扩展需要新的权限: 读取和更改我在github上的数据.  为什么会需要这个权限?

### ISSUE THREAD

**Issue by peroperotina** [labuladong/fucking-algorithm#719]

**Comment by labuladong** [comment]
那是 Chrome 提示的权限信息，实际上插件不会读取和更改你在任何网站的信息，否则无法通过 Chrome web store 的审核。

插件只会访问我的 github 仓库数据，因为后端数据存储在 gitee 和 github 上，当国内 gitee 由于种种原因不稳定时，会去 github 拉取数据，以保证正常使用。
