### ISSUE TITLE
某个疑问

### ISSUE THREAD

**Issue by Andydufresneguohao** [labuladong/fucking-algorithm#733]
我一直在写优质文章，但是后续的文章只发布到公众号/网站/知乎，不能开放到 GitHub。因为本仓库太火了，很多人直接拿我的文章去开付费专栏，价格还不便宜，我这免费写给您看，何必掏冤枉钱呢？所以多多关注本作者，多多宣传，谁也不希望劣币驱逐良币不是么？
难道你写在其他网站就不会被copy了？

**Comment by cinuor** [comment]
> 
> 我一直在写优质文章，但是后续的文章只发布到公众号/网站/知乎，不能开放到 GitHub。因为本仓库太火了，很多人直接拿我的文章去开付费专栏，价格还不便宜，我这免费写给您看，何必掏冤枉钱呢？所以多多关注本作者，多多宣传，谁也不希望劣币驱逐良币不是么？
> 难道你写在其他网站就不会被copy了？

写在github的内容，因为有相关license，所以按道理上说是可以转载或者修改发布的。在别的商业平台上被抄袭的话，是可以追究侵权的

**Comment by labuladong** [comment]
。。。
