### ISSUE TITLE
bug  最长递增子序列dp数组配图错误

### ISSUE THREAD

**Issue by Orabla** [labuladong/fucking-algorithm#739]
你好，我发现如下文章有 bug：

[动态规划系列/动态规划设计：最长递增子序列.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E8%AE%BE%E8%AE%A1%EF%BC%9A%E6%9C%80%E9%95%BF%E9%80%92%E5%A2%9E%E5%AD%90%E5%BA%8F%E5%88%97.md)

问题描述：
该处的dp数组内容应该为12232，图里dp数组元素为原数组的元素。
<img width="358" alt="屏幕截图 2022-03-13 145650" src="https://user-images.githubusercontent.com/47916590/158048987-c4c49239-e2ca-4d7c-aa27-0d4d8fc3db85.png">

**Comment by labuladong** [comment]
谢谢指出，这个确实是画错了，我改下
