### ISSUE TITLE
translate  技术/密码技术.md

### ISSUE THREAD

**Issue by Lsk08** [labuladong/fucking-algorithm#74]
translate  技术/密码技术.md

我已阅读过[翻译组工作流程](https://github.com/labuladong/fucking-algorithm/issues/9)，我已阅读过[翻译要求](https://github.com/labuladong/fucking-algorithm/blob/english/README.md)，我拥有了向主仓库提交 pull request 的权限，会对负责此次翻译的质量。

我将开始翻译如下文章（点击可查看目标文章）：

[技术/密码技术.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E6%8A%80%E6%9C%AF/%E5%AF%86%E7%A0%81%E6%8A%80%E6%9C%AF.md)

我对如何翻译此文章已经心中有数，我准备将它翻译成：**英文**

**预计 7 天内翻译完成**，我会尽可能快地完成翻译，主仓库允许第一个完成的 pull request 添加翻译者昵称/姓名及 Github profile 链接（或任意你希望的链接）。

**Comment by Lsk08** [comment]
I am not sure what happen.So someone have translated the password?

**Comment by labuladong** [comment]
Sorry, that's a mistake... Even if someone has translated it, you can still PR your translation.
