### ISSUE TITLE
bug Github Pages和镜像网站Gitee Pages位置错误

### ISSUE THREAD

**Issue by a-fly-fly-bird** [labuladong/fucking-algorithm#740]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

https://labuladong.gitee.io/algo/4/30/115/

问题描述：
<img width="593" alt="截屏2022-03-14 下午9 02 01" src="https://user-images.githubusercontent.com/70647529/158177818-16395c48-c9df-44d9-92cc-fd9754b8bacf.png">

**Comment by labuladong** [comment]
没看懂有什么问题

**Comment by a-fly-fly-bird** [comment]
不应该国内的是镜像网站吗😁

**Comment by labuladong** [comment]
事实是，国内的网站因为访问量太大，已经有些卡了，所以希望一些人去访问 [github pages](https://labuladong.github.io/algo/)

**Comment by a-fly-fly-bird** [comment]
好的
