### ISSUE TITLE
Linux 管道符原理大揭秘 :: labuladong的算法小抄

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#744]
文章链接点这里：[Linux 管道符原理大揭秘](https://labuladong.github.io/article/fname.html?fname=linux技巧3)

评论礼仪 [见这里](https://mp.weixin.qq.com/s/YdSoYZS0QjZpbphQlpHyyA)，违者直接拉黑。

**Comment by oublie6** [comment]
学到了，多谢东哥
