### ISSUE TITLE
Linux 文件系统都是什么鬼 :: labuladong的算法小抄

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#746]
文章链接点这里：[Linux 文件系统都是什么鬼](https://labuladong.github.io/article/fname.html?fname=linux文件系统)

评论礼仪 [见这里](https://mp.weixin.qq.com/s/YdSoYZS0QjZpbphQlpHyyA)，违者直接拉黑。

**Comment by bingshunjishi** [comment]
如果某个程序崩溃了，可以到 /val/log 中尝试寻找出错信息，到 /tmp 中寻找残留的临时文件。

应为/var/log

**Comment by Wangsh6166** [comment]
东哥这用的啥系统嗷？之前尝试过deepin，老是莫名其妙死机，就放弃了

**Comment by programmeryuan23** [comment]
这是哪个发行版本啊？看起来和macos好像
