### ISSUE TITLE
构造回文的最小插入次数 :: labuladong的算法小抄

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#754]
文章链接点这里：[构造回文的最小插入次数](https://labuladong.github.io/plugin-v4/?qno=1312)

**Comment by zhongweiLeex** [comment]
> 又因为状态转移方程中 dp[i][j] 和 dp[i+1][j]，dp[i]-1]，dp[i+1][j-1] 三个状态有关，为了保证每次计算 dp[i][j] 时，这三个状态都已经被计算，我们一般选择从下向上，从左到右遍历 dp 数组

`二、代码实现` 这一段的 第二张图上面这段文字中， `dp[i][j-1]` 没写完整 ，写成了 `dp[i]-1]`

东哥，关注修改一下小小瑕疵哦。：>

**Comment by labuladong** [comment]
@zhongweiLeex 你看的好仔细啊，印象中你提了好几个错误😂，已修复

**Comment by zhongweiLeex** [comment]
> @zhongweiLeex 你看的好仔细啊，印象中你提了好几个错误😂，已修复

哈哈哈 多谢东哥夸奖，这样比较有参与感和成就感 😄  , 感谢东哥的开源精神，让我们能得到这么好的刷题讲解！
