### ISSUE TITLE
最优子结构原理和 dp 数组遍历方向 :: labuladong的算法小抄

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#759]
文章链接点这里：[最优子结构原理和 dp 数组遍历方向](https://labuladong.github.io/article/fname.html?fname=最优子结构)

评论礼仪 [见这里](https://mp.weixin.qq.com/s/YdSoYZS0QjZpbphQlpHyyA)，违者直接拉黑。

**Comment by Maschinist-LZY** [comment]
1、遍历的过程中，所需的状态必须是已经计算出来的。

2、遍历结束后，存储结果的那个位置必须已经被计算出来。

下面来**距离**解释上面两个原则是什么意思。东哥，这里**具体**解释不小心打成**距离**了哦

**Comment by labuladong** [comment]
@Maschinist-LZY 谢谢指出，已修复~

**Comment by bert82503** [comment]
打卡，感谢！

**Comment by yokiizx** [comment]
斜着遍历没看懂....

**Comment by cillian-bao** [comment]
```
// 斜着遍历数组
for (int l = 2; l <= n; l++) {
    for (int i = 0; i <= n - l; i++) {
        int j = l + i - 1;
        // 计算 dp[i][j]
    }
}
```
斜着遍历数组这里是不是应该写为l=1开始，这样的画是正对角线，否则是正对角线上面一条斜线，不知道dong哥想表达的是那个

**Comment by labuladong** [comment]
@cillian-bao 理解你的意思，正对角线上的是 base case，所以我们进行状态转移是从正对角线上面一条开始

**Comment by billwhn** [comment]
显然，至少有两条路径：(i, j) -> #1 -> #4 和 (i, j) -> #3 -> #3。

第一种是不是写错了
