### ISSUE TITLE
Any chance of English translation?

### ISSUE THREAD

**Issue by manikantag** [labuladong/fucking-algorithm#8]
Hi,

I've few pages using Google Translator, and the translation didn't sound perfect. Still I managed to read this page https://labuladong.gitbook.io/algo/shu-ju-jie-gou-xi-lie/xue-xi-shu-ju-jie-gou-he-suan-fa-de-gao-xiao-fang-fa and you're explanation about the basic DS is very good.

I want to read the whole book, but I wonder if you (or, someone) is planning for English translation? Thanks for the effort.

**Comment by tianhaoz95** [comment]
A quick search would find that Gitbook supports i18n https://docs.gitbook.com/features/internationalization.

To enable the language tab, the owner needs to turn it on and configure in Gitbook, so to support another language, either @labuladong has to config i18n support in Gitbook or someone has to fork this repo.

Translating the whole thing is a huge load of work, a more practical approach will be voting the top requested sections I guess.

**Comment by labuladong** [comment]
OK, the translation will start soon, I'll try to find some way to support English as soon as possible.

**Comment by tianhaoz95** [comment]
once the i18n is turned on i can help with some translation ;)

**Comment by manikantag** [comment]
Great to hear... Please let me know once translation is available or in progress.

**Comment by scultc** [comment]
强啊东少！
Well done, Mr.dong!

**Comment by labuladong** [comment]
English translation has started in this issue #9

**Comment by jemshit** [comment]
@labuladong Hey, thanks for the repo. I think in english version of book, chapter numbers/orders are wrong. In english version, chapter one is "high frequency questions". In Chinese version, it is chapter 4, which makes sense.

**Comment by labuladong** [comment]
@jemshit Fixed. Because at first, "high-frequency questions" has most articles finished the translation, now nearly all articles have finished : )

**Comment by labuladong** [comment]
@manikantag Check out [this branch](https://github.com/labuladong/fucking-algorithm/tree/english), and Gitbook has deployed too.

**Comment by manikantag** [comment]
@labuladong Thanks for the very quick work
