### ISSUE TITLE
translate  动态规划系列/编辑距离.md

### ISSUE THREAD

**Issue by Master-cai** [labuladong/fucking-algorithm#86]
我已阅读过[翻译组工作流程](https://github.com/labuladong/fucking-algorithm/issues/9)，我是按照规定的流程图选择的任务，我开启的 issue 是【参与翻译】。

我已阅读过[翻译要求](https://github.com/labuladong/fucking-algorithm/blob/english/README.md)，我的翻译会按照要求，认真负责。

我正在翻译如下文章（点击可查看目标文章）：

[动态规划系列/编辑距离.md](https://github.com/labuladong/fucking-algorithm/blob/master/动态规划系列/编辑距离.md)

翻译为**英文**。

预计 3 天完成。

**Comment by labuladong** [comment]
无需等待，直接开始翻译即可，主仓库将接受最先提交的 pr 并认定为翻译者。
