### ISSUE TITLE
请求翻译组，english 分支接受各位的翻译成果

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#9]
感谢各位的支持，本仓库两天多就 1.6k star，直接推上 Github Trending 了。让我们走出国门，面向世界吧！参与翻译，你也是本仓库的贡献者，顺带还精通了算法，岂不两全其美？

**Comment by labuladong** [comment]
如果你能够参与翻译，对你有如下好处：

1、锻炼英语（或其他语言）就不用说了，除此之外还可以极大增加算法功力。**翻译就是再创作，和你仅仅读一遍的效果必然是天差地别的**。

2、成为此仓库的贡献者之一。看 star 的增长速度，起码要小火一波，**你是贡献者，无论是吹牛装逼还是写进简历，多有面子**？这也是你实力的证明，勇敢地展示自己的才能，才可能获得更多的机会嘛。

**Comment by labuladong** [comment]
### 参与翻译组的方法，重要：

1、**主要方式是开 issue**，说明你正在翻译其中的某一篇文章，这样防止大家撞车，Github 也好管理。

2、**如果你准备翻译某篇文章，先在 issue 列表中寻找是否有人正在和你做相同的工作**。如果有，那你们的工作就可能冗余，你可以联系他协商或者另选一篇翻译。

3、**如果没有人和你做相同的工作，你可以开新的 issue**，其中设置有一个【参与翻译】的选项，点击那个选项，会有现成的模板和格式教你如何描述 issue，你只需要稍作修改，说明你想翻译哪篇文章即可。

**Comment by labuladong** [comment]
### 具体如何完成翻译工作

最开始我会在仓库中新建一个名叫 `english` 的分支，这个分支包含 `master` 分支的所有文件。英文翻译工作全部在该分支中进行，不涉及其他分支，这样就可以直接在中文文件中逐句翻译。

你先 Fork 本仓库的最新版本到你的 Github，然后把你 fork 的仓库拉取到本地，切换到 `english` 分支，即可根据 issue 中的约定开始翻译你的文章，**不要碰你负责的部分之外的内容**，否则可能会影响后续的合并。

翻译完成后，就可以通过 Pull Request 将你的工作成果合并进本仓库，你就成为本仓库的一位贡献者啦！如果不了解具体操作，可以去搜索一下如何进行 Pull Request，这并不难。

**Comment by surfingbyte** [comment]
翻译方式可以用 Github 的 [Project](https://github.com/features/project-management/) 功能，管理起来更方便，参与者也可以更方便地选择待翻译的文章。

**Comment by rongweihe** [comment]
心动不如行动，报名

**Comment by Tracyliut16** [comment]
来了来了

**Comment by labuladong** [comment]
> 翻译方式可以用 Github 的 [Project](https://github.com/features/project-management/) 功能，管理起来更方便，参与者也可以更方便地选择待翻译的文章。

感谢建议，我简单看了下，这个功能虽然强大，但是大家学习成本比较高，文章量并不大，没这个必要。咱们小项目就用普通的 pull request 协作即可，这也是我以前参与协作的方式，简单门槛低，谁都能参与进来，也方便后续更新等操作。

**Comment by Kenshin-T** [comment]
来了来了，报名

**Comment by Mattao** [comment]
报名咯，周末正好可以尝试一篇

**Comment by minhao1995** [comment]
报名

**Comment by Iruze** [comment]
报名

**Comment by warmingkkk** [comment]
报名，四级没过的可以吗？主要来锻炼自己英语能力有能看看算法

**Comment by Kevin-free** [comment]
抱紧大佬大腿

**Comment by timmmGZ** [comment]
报名，国外留学CS，所以英文必备的，课内专门学数学，大数据和算法，课外专门研究机器学习各种算法，如果有这类算法需要翻译可以帮忙。英语水平可借鉴昨天做的一个AI东西的README.md：https://github.com/timmmGZ/Bounding-Box-Regression-GUI

**Comment by labuladong** [comment]
@timmmGZ 欢迎大佬，阅读一下流程，直接参与，提交 pr 即可

**Comment by hagenbaton** [comment]
报名，cet6来挑战自己

**Comment by shu074** [comment]
> 报名，cet6来挑战自己

**Comment by HuangZiSheng001** [comment]
来观光了

**Comment by miaoxiaozui2017** [comment]
translate fucking-algorithm/算法思维系列/双指针技巧.md

**Comment by NLPpupil** [comment]
第零章 必读系列 不需要翻译吗？我看参与翻译组的方法里提到去看english分支，中文文章是还没有翻译的文章，然而没有翻译的文章里并没有第零章？

**Comment by natsunoyoru97** [comment]
请问现在有翻译成日文的需求吗？除了可以负责英文翻译，日文翻译我可以报名。

**Comment by labuladong** [comment]
@natsunoyoru97 小语种暂时不翻译了吧，工作量太大，目前完成英文就行了～

**Comment by labuladong** [comment]
@NLPpupil 第零章都是其他系列的经典文章，改了下名字而已，哈哈

**Comment by issxjl2015** [comment]
英语太差了，要不然早就参与了

**Comment by freerambo** [comment]
这么好的项目，赶紧入手。翻译我是专业的，任务拿过来。加我入组

**Comment by Wonderxie** [comment]
报名！看了一下还剩最后一个《团灭 LeetCode 股票买卖问题》
