### ISSUE TITLE
《辐射4/自由之路》消失

### ISSUE THREAD

**Issue by zhongweiLeex** [labuladong/fucking-algorithm#903]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

https://labuladong.gitee.io/algo/3/27/88/ 

问题描述：

文章页面消失， 88 87 两页都是 地下城游戏那一题

**Comment by labuladong** [comment]
你清除一下浏览器或者多刷新几次页面，就能解决这个 bug

原因：由于技术原因，每次我调整网站目录顺序，很多文章的链接都会改变，你访问到了新的 url，但缓存中存着旧的页面 html，所以导致了你的这个问题

**Comment by zhongweiLeex** [comment]
明白，感谢东哥！

labuladong ***@***.***> 于2022年3月24日周四 12:51写道：
