### ISSUE TITLE
移动到标题题栏上方之后，就移动不下来了。 可选中移动的区域被遮挡，只有卸载重装后才能恢复。

### ISSUE THREAD

**Issue by zzhi123** [labuladong/fucking-algorithm#911]
![image](https://user-images.githubusercontent.com/67152703/164593457-70f9596a-214b-4f0b-a286-df889b965b42.png)

**Comment by labuladong** [comment]
收到，下个版本修复。另外，bug 在这里反馈：https://github.com/labuladong/fucking-algorithm/discussions/704

**Comment by labuladong** [comment]
[V3.5.1](https://mp.weixin.qq.com/s/wIxflO1dvXzDlibhEcENcQ) 版本已解决这个问题
