### ISSUE TITLE
vscode 刷题辅助插件 bug 反馈区

### ISSUE THREAD

**Issue by fengbeibei** [labuladong/fucking-algorithm#917]
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/19942192/165475753-8bdce983-f7e8-414e-8b74-1a0714ed5b27.png">
mac上的插件，1.2和1.3版本都试了，点击code now报错

**Comment by labuladong** [comment]
是你没给 home 目录的磁盘写权限哈，给一下就好了
