### ISSUE TITLE
算法时空复杂度分析实用指南 :: labuladong的算法小抄

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#927]
文章链接点这里：[算法时空复杂度分析实用指南](https://labuladong.github.io/article/fname.html?fname=时间复杂度)

评论礼仪 [见这里](https://mp.weixin.qq.com/s/YdSoYZS0QjZpbphQlpHyyA)，违者直接拉黑。

**Comment by liang734** [comment]
等比数列求和公式是 （k^N - 1）/(k - 1)

**Comment by bruceeewong** [comment]
20230104 打卡
