### ISSUE TITLE
Linux 的进程/线程/文件描述符是什么 :: labuladong的算法小抄

### ISSUE THREAD

**Issue by labuladong** [labuladong/fucking-algorithm#929]
文章链接点这里：[Linux 的进程/线程/文件描述符是什么](https://labuladong.github.io/article/fname.html?fname=linux进程)

评论礼仪 [见这里](https://mp.weixin.qq.com/s/YdSoYZS0QjZpbphQlpHyyA)，违者直接拉黑。

**Comment by whyzxmsodiao** [comment]
牛逼

**Comment by achao-c** [comment]
写的真好，不过files是个指针指向内核中的文件指针数组。图中少画了一步指针寻址。
