### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by scottyyf** [labuladong/fucking-algorithm#975]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[url for leetcode-cn problem list not exist](https://mp.weixin.qq.com/s/wIxflO1dvXzDlibhEcENcQ)

问题描述：

https://leetcode-cn.com/problem-list/59jEaTgw/ is not exist

**Comment by labuladong** [comment]
目前力扣不允许分享题单，所以所有分享的题目列表都是 404

**Comment by labuladong** [comment]
只能等他们官方修复一下这个问题了
